### ISSUE TITLE
lz4 compression codec not found even after installing lz4 module

### ISSUE THREAD

**Issue by suryaprabhakark** [aio-libs/aiokafka#1032]
Hi, 
Had the issue of missing lz4 compression codec, spent 2 hours trying different things with linux, mac. Atlast realised that cramjam package is missing for the codec to work from code which is throwing error. Either we should add cramjam as dependency or update the ReadMe. If its already mentioned somewhere and I missed it, please point me towards the doc.

```
aiokafka.errors.UnsupportedCodecError: UnsupportedCodecError: Libraries for lz4 compression codec not found
```

Thanks

**Comment by vmaurin** [comment]
There is an helper for that (so you don't have to specify cramjam directly, in case it changes), it is in the documentation
https://aiokafka.readthedocs.io/en/stable/#optional-lz4-install

**Comment by vmaurin** [comment]
The doc is wrong about this though (since it was removed)

> aiokafka requires the [kafka-python](https://github.com/dpkp/kafka-python) library.

**Comment by suryaprabhakark** [comment]
Thanks @vmaurin, I didnt realised that there is docs links https://aiokafka.readthedocs.io/. I suggest to have the same wlecome page content in the ReadMe.md, which will help a lot.

**Comment by suryaprabhakark** [comment]
@vmaurin You can close the issue.

**Comment by ods** [comment]
Thank you, added [the link to the documentation](https://github.com/aio-libs/aiokafka/blob/master/README.rst#documentation)
