### ISSUE TITLE
ClusterMetadata, `update_metadata(...)` always fails when following `request_update()` call

### ISSUE THREAD

**Issue by jackgene** [aio-libs/aiokafka#1055]
**Describe the bug**
On ClusterMetadata, an `update_metadata(...)` call following a `request_update()` call always fails.

This is because `update_metadata(...)` is calling:
- [concurrent.future.Future#success(...)](https://github.com/aio-libs/aiokafka/blob/01c60cd9c45e975aee8d4932247108a9e639d026/aiokafka/cluster.py#L310)
- [concurrent.future.Future#failure(...)](https://github.com/aio-libs/aiokafka/blob/01c60cd9c45e975aee8d4932247108a9e639d026/aiokafka/cluster.py#L212)

Both of which do not exist.

**Expected behaviour**
The correct `concurrent.futures.Future` API is used, and no exception is thrown.

**Environment (please complete the following information):**
 - aiokafka version: 0.11.0
 - Kafka Broker version: N/A (not a Kafka issue)
 - Other information: N/A

**Reproducible example**
```python
    cluster = ClusterMetadata()
    updated_cluster = cluster.request_update()
    # This always fails:
    cluster.update_metadata(
        MetadataResponse[0]([(0, "foo", 12), (1, "bar", 34)], []),
    )
```

**Comment by ods** [comment]
Hi @jackgene, thank you for the contribution! You're right, something weird is here, but it doesn't look as simple as in your MR. How did you get this error? I don't see any place where `request_update()` is called, so `self._future` should be always `None`.

**Comment by jackgene** [comment]
> Hi @jackgene, thank you for the contribution! You're right, something weird is here, but it doesn't look as simple as in your PR. How did you get this error? I don't see any place where `request_update()` is called, so `self._future` should be always `None`.

Yeah, I don't think it's called within the library. I think it's just something that could potentially happen if a client calls `request_update()`. I discovered these two weird `future` calls as they were flagged by Pyright during type checking.
