### ISSUE TITLE
please provide python 3.13 support

### ISSUE THREAD

**Issue by sugadge** [aio-libs/aiokafka#1058]
the package is not getting installed on python 3.13.0

**Comment by ods** [comment]
Hi @sugadge,
What error do you get? There is no precompiled binaries for Python 3.13 (and aiokafka can't benefit from using Limited API until it's implemented in Cython, see https://github.com/cython/cython/issues/2542), but should be installable from source package.

**Comment by ods** [comment]
Version 0.12.0 includes pre-built wheel for Python 3.13.

**Comment by sugadge** [comment]
I have not compiled from source as the prod systems source from pypi
repository.
