### ISSUE TITLE
[QUESTION] Long running process prevents auto-commit

### ISSUE THREAD

**Issue by 24dlong** [aio-libs/aiokafka#1059]
# Problem Statement
I'm trying to figure out the best way to prevent the following series of errors encountered while running my `AIOKafkaConsumer`.

```
OffsetCommit failed for group my-group due to group error ([Error 25] UnknownMemberIdError: my-group), will rejoin
Auto offset commit failed: [Error 25] UnknownMemberIdError: my-group
Heartbeat failed: local member_id was not recognized; resetting and re-joining group
Heartbeat session expired - marking coordinator dead
Marking the coordinator dead (node 0)for group my-group.
```

I'm trying to trigger a long-running process on receipt of my kafka message. From what I've determined in my debugging
* This long-running process blocks a `GroupCoordinator._maybe_do_autocommit()` call
* Since Kafka doesn't receive a heartbeat from my consumer within the `session_timeout_ms`, it triggers a rebalance of the consumer group, my consumer's partition is revoked, and the offset fails.

This is becoming problematic because when multiple consumers are running within the group, the message gets passed from consumer to consumer and ends up locking up the entire group and leading to re-processing.

After adding a `print()` statement to the `_maybe_do_autocommit()` in my local copy of the library, it also seems if multiple events are received at the same time, the consumer finishes processing all events before sending another heartbeat.

```
_maybe_do_autocommit() attempt
Started message processing for offset:  43
Finished message processing for offset:  43
Started long-running subprocess for offset:  43
Finished long-running subprocess for offset 43 in 18.13497162499698 seconds
_maybe_do_autocommit() attempt
Started message processing for offset:  44
Finished message processing for offset:  44
Started message processing for offset:  45
Finished message processing for offset:  45
Started message processing for offset:  46
Finished message processing for offset:  46
Started long-running subprocess for offset:  44
Finished long-running subprocess for offset 44 in 18.029142750019673 seconds
Started long-running subprocess for offset:  45
Finished long-running subprocess for offset 45 in 17.999060582951643 seconds
Started long-running subprocess for offset:  46
Finished long-running subprocess for offset 46 in 18.02505141601432 seconds
_maybe_do_autocommit() attempt
OffsetCommit failed for group my-group due to group error ([Error 25] UnknownMemberIdError: my-group), will rejoin
OffsetCommit failed for group my-group due to group error ([Error 25] UnknownMemberIdError: my-group), will rejoin
Auto offset commit failed: [Error 25] UnknownMemberIdError: my-group
Heartbeat failed: local member_id was not recognized; resetting and re-joining group
Heartbeat session expired - marking coordinator dead
Marking the coordinator dead (node 0)for group my-group.
_maybe_do_autocommit() attempt
```

This behavior can be reproduced in the sample consumer below.

## Sample Consumer

```py
from aiokafka import AIOKafkaConsumer
import asyncio
import time


def fibonacci(n: int) -> int:
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)


async def long_running_process(msg):
    print("Started long-running subprocess for offset: ", msg.offset)
    start = time.perf_counter()
    fibonacci(41)
    end = time.perf_counter()
    print(
        f"Finished long-running subprocess for offset {msg.offset} in "
        f"{(end-start)} seconds"
    )


async def consume():
    consumer = AIOKafkaConsumer(
        'my_topic',
        bootstrap_servers='localhost:9092',
        group_id="my-group",
    )
    # Get cluster layout and join group `my-group`
    await consumer.start()
    try:
        # Consume messages
        async for msg in consumer:
            print("Started message processing for offset: ", msg.offset)
            asyncio.create_task(long_running_process(msg))
            print("Finished message processing for offset: ", msg.offset)

    finally:
        # Will leave consumer group; perform autocommit if enabled.
        await consumer.stop()

asyncio.run(consume())
```

## Sample Producer
```py
from aiokafka import AIOKafkaProducer
import asyncio


async def send_one():
    producer = AIOKafkaProducer(
        bootstrap_servers='localhost:9092'
    )
    # Get cluster layout and initial topic/partition leadership information
    await producer.start()
    try:
        # Produce message
        await producer.send_and_wait("my_topic", b"Super message")
    finally:
        # Wait for all pending messages to be delivered or expire.
        await producer.stop()

asyncio.run(send_one())
```

# Questions
As per the (aiokafka docs)[https://aiokafka.readthedocs.io/en/stable/kafka-python_difference.html#rebalances-are-happening-in-the-background], since "aiokafka delegates heartbeating to a background Task and will send heartbeats to Coordinator as long as the event loop is running", I'm expecting not to see unnecessary rebalances.

I'm either not understanding this statement correctly, or things aren't quite working as I'd expect.

My expected behavior here is as follows:
1) Consumer receives message
2) Consumer kicks off the long-running process
3) Consumer commits offset with iteration of the loop completing
4) Long-running process finishes in the background

All the while, every 3 seconds, another "thread" is running a background task to send a heartbeat every 3 seconds (the default of `heartbeat_interval_ms`), so a rebalance is never triggered.

So my questions are as follows:
1) If I'm not understanding the docs correctly, where am I getting turned around?
2) If it's not possible to get my consumer working as desired, is it still possible to support this consumer in some way while still using auto offsets? It seems increasing `session_timeout_ms` to a value greater than my long running process' processing time fixes the issue - but if multiple events are received at the same time, then the `session_timeout_ms` needs to be greater than the processing time of all events. This means that I'll need to raise `session_timeout_ms` to a significantly higher value than the default (likely 2 mins) to account for a burst of messages and I'd prefer a solution that doesn't count on a maximum number of events coming in during a set interval.
3) Are there other implications of setting `session_timeout_ms` to such a high value (such as 2 minutes)?
4) Depending on the answers above, it seems to me like my best path forward is as follows. Does this align with the intended usage of this library in this case?
    1) Migrate to using manual commits
    2) Increase `session_timeout_ms` to a value greater than a single run of my long running process (don't have to worry about message chaining)
    3) Commit after each message
    
    Like so:
    ```
    async def consume():
        consumer = AIOKafkaConsumer(
            'my_topic',
            bootstrap_servers='localhost:9092',
            group_id="my-group",
            session_timeout_ms=22000,
            enable_auto_commit=False
        )
        # Get cluster layout and join group `my-group`
        await consumer.start()
        try:
            # Consume messages
            async for msg in consumer:
                print("Started message processing for offset: ", msg.offset)
                asyncio.create_task(long_running_process(msg))
                print("Committing offset: ", msg.offset)
                await consumer.commit()
                print("Committed offset: ", msg.offset)
                print("Finished message processing for offset: ", msg.offset)
    
        finally:
            # Will leave consumer group; perform autocommit if enabled.
            await consumer.stop()
    ```

**Comment by vmaurin** [comment]
The issue here is that no threads are involved, it is python asyncio "task". All asyncio tasks are running within the same threads, part of an event loop, so here basically, your long running process is blocking the whole event loop, preventing all the other tasks to run. The asyncio model is to run thing concurrently and not in parallel. So here you have two options: 
* running your long task in an other thread/thread pool (there are some libs out there to simplify that)
* yielding (i.e calling await) in your long running process to give opportunity to other tasks to run (in you fib example, you can add an `await asyncio.sleep(0)` to do so)

**Comment by 24dlong** [comment]
Thanks @vmaurin, here's what I ended up implementing, in case this helps anyone else. Using asyncio.to_thread to run my process on a separate thread and not block the event loop.

```
async def consume():
    consumer = AIOKafkaConsumer(
        'my_topic',
        bootstrap_servers='localhost:9092',
        group_id="my-group"
    )
    # Get cluster layout and join group `my-group`
    await consumer.start()
    try:
        # Consume messages
        async for msg in consumer:
            print("Started message processing for offset: ", msg.offset)
            await asyncio.to_thread(asyncio.run, long_running_process(msg))
            print("Committing offset: ", msg.offset)
            await consumer.commit()
            print("Committed offset: ", msg.offset)
            print("Finished message processing for offset: ", msg.offset)

    finally:
        # Will leave consumer group; perform autocommit if enabled.
        await consumer.stop()
```
