### ISSUE TITLE
Cannot Build RPM

### ISSUE THREAD

**Issue by nadersalehi** [aio-libs/aiokafka#11]
RPM build fails as it cannot find CHANGES.rst

> python3 setup.py bdist_rpm
> <snip>
> + STATUS=0
> + '[' 0 -ne 0 ']'
> + cd aiokafka-0.0.1
> + /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
> + exit 0
> Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.iKQpUb
> + umask 022
> + cd /home/salehi/projects/need-seek/backend/aiokafka-master/build/bdist.linux-x86_64/rpm/BUILD
> + cd aiokafka-0.0.1
> + python3 setup.py build
> Traceback (most recent call last):
>   File "setup.py", line 53, in <module>
>     long_description='\n\n'.join((read('README.rst'), read('CHANGES.rst'))),
>   File "setup.py", line 20, in read
>     return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
> FileNotFoundError: [Errno 2] No such file or directory: 'CHANGES.rst'
> error: Bad exit status from /var/tmp/rpm-tmp.iKQpUb (%build)
> 
> 
> RPM build errors:
>     Bad exit status from /var/tmp/rpm-tmp.iKQpUb (%build)
> error: command 'rpmbuild' failed with exit status 1

**Comment by asvetlov** [comment]
The library has not released yet BTW.

**Comment by nadersalehi** [comment]
Speaking of the release, do you have planned date?  I desperately need an asynio-based kafka library and would be delighted to use this module.  If there is anything to do to expedite the release, please let me know.

I have very limited free time but am willing to contribute to the code base.

**Comment by asvetlov** [comment]
No idea for now. Maybe I'll find some time next week to review current aiokafka code and make the first release.

**Comment by Drizzt1991** [comment]
There's no way to reproduce this. Anyway it should be fixed by v0.1.1 patch, if not - please create new issue.
