### ISSUE TITLE
Missing requirement for tests in README.rst

### ISSUE THREAD

**Issue by Artimi** [aio-libs/aiokafka#145]
In `README.rst` there is written that all you need to do is:
1. Install `docker`
2. Install `libsnappy-dev`
3. run `make setup`
4. run `make test`

However after few hours I've discovered that you need to have installed also utility `keytool` https://docs.oracle.com/javase/6/docs/technotes/tools/solaris/keytool.html that is part of Java (not installed on my computer before). It is used in script `gen-ssl-certs.sh` to generate few files and one of them was `br_server.keystore.jks`. `gen-ssl-certs.sh` on tests start silently failed and didn't make those files. Kafka in docker then failed everytime it tried to start on exception:
```
org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: java.io.FileNotFoundException: /ssl_cert/br_server.keystore.jks (No such file or directory)
```
I recommend to update README with `keytool` requirements and also raise exception in fixture `ssl_folder.py` if `gen-ssl-certs.sh` does not return 0.

**Comment by Drizzt1991** [comment]
Yea, took the `gen-ssl-certs.sh` from libdrkafka, kinda assumed it only uses openssl. Will think of how to better fix this. You can't actually start current docker image without valid certificates.
