### ISSUE TITLE
Use loop.create_future instead of asyncio.Future

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiokafka#156]
We should use `AbstractEventLoop.create_future()` in order to create futures bounded to the event loop, since third party event loop may provide custom `asyncio.Future` implementation. `uvloop` has its own implementation in C.

**Comment by Drizzt1991** [comment]
Fair, not so hard to implement. Will probably add something like we did with `ensure_future`.

**Comment by jettify** [comment]
Sure, you can create label `easy` and also tag `help-wanted` (like aiohttp does), to encourage new contributors.

**Comment by tvoinarovskyi** [comment]
Fixed by #221
