### ISSUE TITLE
Topic leaders change/broker crash causes aiokafka to stop producing messages

### ISSUE THREAD

**Issue by blugowski** [aio-libs/aiokafka#176]
### Version information:
Kafka cluster: 0.10.2.1
aiokafka: 0.2.2 (kafka-python 1.3.1)
Python: 3.5.2

### Producer script:
```
import asyncio
from aiokafka import AIOKafkaProducer

@asyncio.coroutine
def produce(loop):
    while True:
        resp = yield from producer.send_and_wait('my-topic', value=b'some_message_bytes')
        print("Message produced: partition {}; offset {}".format(resp.partition, resp.offset))
        yield from asyncio.sleep(1)

loop = asyncio.get_event_loop()
producer = AIOKafkaProducer(loop=loop, bootstrap_servers='bootstrap-server1:9092,bootstrap-server2:9092,bootstrap-server3:9092')
loop.run_until_complete(producer.start())
loop.run_until_complete(produce(loop))
loop.run_until_complete(producer.stop())
loop.close()
```

### Bug reproduce flow:
1. Start producer script, it will send message every 1 second.
2. Stop one of Kafka brokers(partitions leaders will change).
3. Script stops producing messages, no logs, anything, just hangs.

If you send kill command to the script, you will see this exception:
```
Task exception was never retrieved
future: <Task finished coro=<AIOKafkaProducer._send_produce_req() done, defined at lib/python3.5/site-packages/aiokafka/producer.py:331> exception=ValueError(<class 'struct.error'>,)>
Traceback (most recent call last):
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 17, in _unpack
    (value,) = unpack(f, data)
struct.error: unpack requires a bytes object of length 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "lib/python3.5/site-packages/aiokafka/producer.py", line 365, in _send_produce_req
    response = yield from self.client.send(node_id, request)
  File "lib/python3.5/site-packages/aiokafka/client.py", line 375, in send
    request, expect_response=expect_response)
  File "lib/python3.5/site-packages/aiokafka/conn.py", line 141, in send
    message = header.encode() + request.encode()
  File "lib/python3.5/site-packages/kafka/protocol/struct.py", line 34, in _encode_self
    [self.__dict__[name] for name in self.SCHEMA.names]
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 124, in encode
    for i, field in enumerate(self.fields)
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 124, in <listcomp>
    for i, field in enumerate(self.fields)
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 162, in encode
    [self.array_of.encode(item) for item in items]
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 162, in <listcomp>
    [self.array_of.encode(item) for item in items]
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 124, in encode
    for i, field in enumerate(self.fields)
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 124, in <listcomp>
    for i, field in enumerate(self.fields)
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 162, in encode
    [self.array_of.encode(item) for item in items]
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 162, in <listcomp>
    [self.array_of.encode(item) for item in items]
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 124, in encode
    for i, field in enumerate(self.fields)
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 124, in <listcomp>
    for i, field in enumerate(self.fields)
  File "lib/python3.5/site-packages/kafka/protocol/message.py", line 154, in encode
    size = Int32.decode(items)
File "lib/python3.5/site-packages/kafka/protocol/types.py", line 50, in decode
    return _unpack('>i', data.read(4))
  File "lib/python3.5/site-packages/kafka/protocol/types.py", line 20, in _unpack
    raise ValueError(error)
ValueError: <class 'struct.error'>
```

We are looking into this, but feel free to comment.

**Comment by ngavrysh** [comment]
@blugowski @Drizzt1991  Hey guys. We've got the same issue. I've committed the fix to our aiokafka fork : https://github.com/Tubular/aiokafka.
If the batch send is not successful then producer tries to process the batch again, BUT batch's buffer is already read after the first attempt. That's why the background task crashes silently.

**Comment by Drizzt1991** [comment]
Hi guys, wanted to let you know on the status for this. I've confirmed the problem, currently debugging some problems with it, should manage to get a fix in near time.
@ngavrysh Thanks a lot, probably that should fix #173 =). Sadly in this case, there's another problem going on here. Still going through it.

**Comment by tvoinarovskyi** [comment]
@blugowski Yea, so there's a bad design here. We always retry to the same node, without checking for Leader change. It will take some time to correct it, as Java's code is really hard in this part. Will keep it touch

**Comment by blugowski** [comment]
@tvoinarovskyi Ok. We have removed retries as a temporary workaround, so each exception is going to the top and we can retry this request "manualy".

**Comment by tvoinarovskyi** [comment]
@blugowski Well I do have a fix already in branch v0.2. Would it be hard to test if it works? I planned to release it as 0.2.3 bugfix, but want to confirm that it resolves the issue. I did try locally, worked for me.

**Comment by blugowski** [comment]
@tvoinarovskyi Great! We will test it asap.

**Comment by tvoinarovskyi** [comment]
@blugowski I plan to release the branch tomorrow, hope it fixed the issue for you.

**Comment by blugowski** [comment]
@tvoinarovskyi sorry for the delay.
In a simple test, like stop and start broker it works well, it retries and continues sending. But it fails in broker crash test.

Reproduce flow:
1. Kafka cluster has 3 brokers: broker-server1, broker-server2, broker-server3; topic: 9 partitions; replication: 2.
2. Shutdown one of the brokers VM/host, ex. broker-server2.
3. `KafkaTimeoutError`(no `retriable` param, so it is set to `False`: https://github.com/dpkp/kafka-python/blob/1.3.1/kafka/errors.py#L355) is raised, so we can catch it and send message again. Producer is working normal.
4. Start new VM/host and broker: broker-server4. Cluster has now 3 brokers: broker-server1, broker-server3, broker-server4.
5. `UnknownTopicOrPartitionError` is raised after reassigning partitions/leaders:

```
DEBUG:aiokafka.conn:<AIOKafkaConnection host=broker-server1 port=9092> Response 291: ProduceResponse_v2(topics=[(topic='my-topic', partitions=[(partition=7, error_code=3, offset=-1, timestamp=-1)])], throttle_time_ms=0)
Traceback (most recent call last):
  File "producer.py", line 27, in <module>
    loop.run_until_complete(produce(loop))
  File "python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "producer.py", line 15, in produce
    resp = yield from producer.send_and_wait('my-topic', value=b'some_message_bytes')
  File "python3.6/site-packages/aiokafka/producer.py", line 286, in send_and_wait
    return (yield from future)
kafka.errors.UnknownTopicOrPartitionError: [Error 3] UnknownTopicOrPartitionError:
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<AIOKafkaProducer._sender_routine() running at python3.6/site-packages/aiokafka/producer.py:337> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa95ccc0dc8>()]>>
```

After raising `UnknownTopicOrPartitionError` client should update metadata and retry(https://github.com/dpkp/kafka-python/blob/1.3.1/kafka/errors.py#L113). Or am I wrong?

**Comment by tvoinarovskyi** [comment]
Cool, thanks, I'll try to reproduce the issue. I have a hunch about the KafkaTimeoutError issue, will fix that. UnknownTopicOrPartitionError is more interesting, will try to get the same.

**Comment by tvoinarovskyi** [comment]
@blugowski Hi there, sorry but I fail to reproduce the case. Maybe I don't understand the steps enough. 
1) If you have 3 nodes: `broker-server1`, `broker-server2`, `broker-server3`, and you shut down `broker-server2` you will end up with a normal, working cluster. As replication is set to 2, we will have at least 1 replica, which will be the new leader. In my case it changed to:
```
vagrant@my-dev:/workspace/kafka_2.11-0.10.1.0$ bin/kafka-topics.sh --describe --zookeeper localhost:2181 --topic my-replicated-topic
Topic:my-replicated-topic       PartitionCount:9        ReplicationFactor:2     Configs:
        Topic: my-replicated-topic      Partition: 0    Leader: 1       Replicas: 1,2  Isr: 1
        Topic: my-replicated-topic      Partition: 1    Leader: 0       Replicas: 2,0  Isr: 0
        Topic: my-replicated-topic      Partition: 2    Leader: 0       Replicas: 0,1  Isr: 0,1
        Topic: my-replicated-topic      Partition: 3    Leader: 1       Replicas: 1,0  Isr: 0,1
        Topic: my-replicated-topic      Partition: 4    Leader: 1       Replicas: 2,1  Isr: 1
        Topic: my-replicated-topic      Partition: 5    Leader: 0       Replicas: 0,2  Isr: 0
        Topic: my-replicated-topic      Partition: 6    Leader: 1       Replicas: 1,2  Isr: 1
        Topic: my-replicated-topic      Partition: 7    Leader: 0       Replicas: 2,0  Isr: 0
        Topic: my-replicated-topic      Partition: 8    Leader: 0       Replicas: 0,1  Isr: 0,1
```
If I add a new node, say `broker-server4` it does not allocate any partitions to it... It just waits for `broker-server2` to become online again. What did you mean by `after reassigning partitions/leaders`, do I need to force a reassign somehow?

2) What VM's do you use to check this setup? If I use something like `kill -9` to kill brokers on local machine, I don't get the desired behaviour of `KafkaTimeoutError`.

**Comment by blugowski** [comment]
@tvoinarovskyi 
1. Yes, I forced reassign process. This test covers case when cluster topology changes permanently(old host will never be up again).
2. I destroy VM. I see that you are using Vagrant, so probably you should use `destroy` command: https://www.vagrantup.com/docs/cli/destroy.html Each broker has own VM(Vagrant instance), so you should destroy one of them, and run completly new one(new IP, new name).

**Comment by tvoinarovskyi** [comment]
@blugowski Thanks I could reproduce the problem. What struck me is that `kafka-python` actually raised the same `UnknownTopicOrPartitionError` error during reassignment process. Will do a few other tests, maybe there's actually no way around this...

**Comment by tvoinarovskyi** [comment]
@blugowski Hey there, the latest changes should contain fixes for the mentioned problems. `UnknownTopicOrPartitionError ` is fixed with a temporary patch, that I will remove after we fix it in `kafka-python`, but for you it should be without any error.

**Comment by tvoinarovskyi** [comment]
I thinks I'll just release v0.2.3 asap, it should still be better than v0.2.2. If we find new problems it will go into the next release/patch.

**Comment by tvoinarovskyi** [comment]
@blugowski Released v0.2.3.

**Comment by blugowski** [comment]
@tvoinarovskyi Thank you for quick fix! I will check new version today.

**Comment by blugowski** [comment]
@tvoinarovskyi Now it's working good when leaders are changing(`UnknownTopicOrPartitionError` is properly handled). But I see that `RequestTimedOutError` is raised when broker goes down and it's not catched(crashes sample producer script from first post). Shouldn't request be retried?

**Comment by tvoinarovskyi** [comment]
@blugowski Thats a big **design problem**. The deal is that RequestTimedOutError - is the error Broker was raising before and clients should have reacted to it (it's raised if not all replicas replied before ack level was reached). In v0.2.2 and before this error was propagated to application level. So current implementation in v0.2.3 should not break much. Basically:
 * In 0.2.2 you had `KafkaTimeoutError` if request timeouts either on buffer append (send() coroutine) or on request timeout (if you wait on returned future). `RequestTimedOutError` - in case of a timeout on inner-broker communication.
 * In 0.2.3 you will only have `KafkaTimeoutError` in case of timeout during buffer space append. And `RequestTimedOutError` in request timeout or inner-broker communication.
Also you can have a lot of other errors in v0.2.3, basically any KafkaError, that occured after request timed out will propagate to application.

In `kafka-python` it's not really defined either which errors can be raised on future awaiting, but `send()` will always raise KafkaTimeoutError. Basically the problem stands even for java's client, did not find any error specification what is raised when (like https://kafka.apache.org/0101/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html, not really much you can do with error in callback except logging it).

**Comment by tvoinarovskyi** [comment]
@blugowski So to answer you're question, it is raised because the request actually times out as per `request_timeout_ms` configuration, but I changed the error in v0.2.3 to `RequestTimedOutError` to match `kafka-python` implementation of that part. I'm opened for suggestions here, but I think this is how kafka works, it's where you get either duplicate or missed produce's

**Comment by blugowski** [comment]
@tvoinarovskyi Ok, so answer is to let the user decide what want to do in this case. I think it will be good to mention about it in docs/examples. Thank you for explanation.

I'm closing this issue. @tvoinarovskyi thanks again for quick response and fix.
