### ISSUE TITLE
Kafka Exactly Once Semantics Support (Kafka 0.11.0.x)

### ISSUE THREAD

**Issue by vineetgoel** [aio-libs/aiokafka#182]
Is there a plan on when aiokafka will support the newly added exactly once semantics using Idempotent and Transactional Producers?

**Comment by tvoinarovskyi** [comment]
I will definitely work on this, but `aiokafka` needs a lot of old features finished, so I would expect `kafka-python` to have the feature first. Do you have a need for exactly Transactional Producer, or you would be ok with Indempotent delivery. The later is much easier and will probably be the first goal.

**Comment by tvoinarovskyi** [comment]
Lets add the [KIP-98](https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging) link here

**Comment by vineet-rh** [comment]
I think we would need both of them for our use-case.

**Comment by tvoinarovskyi** [comment]
I start development of Transactional producer and plan to finish it till the end of this month, as I will have some spare time.

**Comment by tvoinarovskyi** [comment]
If there are suggestions on how the API should be structured, would be glad to hear. @ask @vineetgoel

**Comment by vineetgoel** [comment]
@tvoinarovskyi sorry about the late response. The standard API (in the java clients) should work well for us.

Particularly the things we would need are:
- Idempotent flag on the producer
- Consumer transactional flag
- Producer start transaction
- Producer commit offsets and end transaction;

We will typically be sending a bunch of messages in a transaction and then committing offsets and ending the transaction.

While reading, we would typically only want to read committed transactions.

**Comment by tvoinarovskyi** [comment]
@vineetgoel The implementation was merged to master if you have time/eagerness I'm open to API suggestions or fixups. Hope will release it as 0.5 this year ;)
Thanks for the patience, was a long year with this!

**Comment by tvoinarovskyi** [comment]
Released as part of v0.5.0
