### ISSUE TITLE
Do we even need to support old Kafka versions?

### ISSUE THREAD

**Issue by Drizzt1991** [aio-libs/aiokafka#20]
In process of porting `python-kafka` code to `asyncio` I can see many places, that require version-dependant management of Kafka cluster. The author of `python-kafka` fixed those in process, but I have no idea why and what were the issues. It's hard to understand some concepts and just blindly port them I think will resolve in quite some _support_ work to do.
For now I think we should focus on the Last Kafka release - 0.9. I can understand the need to support old clusters, as most of the existing ones are older. I doubt there are alot of 0.9 production environments (if any). But the driver was never released and 0.9 has very [big changes in cluster management of the consumer](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Detailed+Consumer+Coordinator+Design). 
We can always add backward compatibility after we review the 0.9 code good enough.
Any objections?

**Comment by asvetlov** [comment]
I don't think if we need to support old kafka servers.

**Comment by Drizzt1991** [comment]
For now we limit the driver to Kafka 9+ to support full-feature GroupCoordinator. Closing the issue
