### ISSUE TITLE
Docs and/or examples?

### ISSUE THREAD

**Issue by popravich** [aio-libs/aiokafka#21]
Any plans to make docs and examples?

**Comment by TarasLevelUp** [comment]
Yup, as soon as we get it running and finish up with high level interface. I still think, that we can do better than python-kafka. I think to the end of the next week we will have working high level stuff ready.

**Comment by popravich** [comment]
oh, I was thinking it work already)

**Comment by TarasLevelUp** [comment]
I does =) But I wanna change some interface stuff.

**Comment by Drizzt1991** [comment]
Merged the consumer branch. Docs under way, will push some examples on this week (maybe tomorrow).

**Comment by Drizzt1991** [comment]
Very basic examples are present in README of v0.9 branch

**Comment by Drizzt1991** [comment]
Done
