### ISSUE TITLE
OverflowError still exists in pip standard package

### ISSUE THREAD

**Issue by CharAct3** [aio-libs/aiokafka#214]
> ref uvloop OverflowError in fetcher has been fixed(https://github.com/aio-libs/aiokafka/pull/210)

Hello! I installed `aiokafka` from pip, and used it with `uvloop`, but there's an error in `fetcher.py`.

And I found it has been fixed, but it still exists in pip standard package(`aiokafka-0.3.0`).

I think I should inform about it.

Sorry for the inconvenience😓.

**Comment by tvoinarovskyi** [comment]
Yes, there was no bugfix done after that, so did not release it. Will get it out on weekend if you need it.

**Comment by jkgeyti** [comment]
I'm running into the same problem, so a push would be great!

**Comment by tvoinarovskyi** [comment]
Set up a release build. Should be done in half an hour. Sorry for the wait, the master branch was not ready for a release, had to update it.

**Comment by CharAct3** [comment]
@tvoinarovskyi Thanks for your time!😊
