### ISSUE TITLE
Allow direct batch access in the Producer

### ISSUE THREAD

**Issue by shargan** [aio-libs/aiokafka#216]
Spawned from https://github.com/aio-libs/aiokafka/pull/215

I have a use-case where my incoming stream cannot be advanced until messages are delivered. Doing so right now requires calling `await producer.send_and_wait(...)` in a loop which is terribly inefficient. Since Kafka writes entire MessageSets at once, having the ability to create, fill, and send batches directly would give me the fine control I need with far greater throughput.

The PR linked above is a functional first stab at this.

**Comment by tvoinarovskyi** [comment]
Do I understand correctly, that you want to achieve:
```python
consumer = AIOKafkaConsumer(bootstrap_servers=consuming_cluster_servers)
producer = AIOKafkaProducer(bootstrap_servers=producing_cluster_servers)
consumer.subscribe(["topic1", "topic2"])

async for msg in consumer:
    await producer.send(value=msg.value, key=msg.key, timestamp=msg.timestamp)

```

**Comment by tvoinarovskyi** [comment]
The code above will fetch messages as batches and send batch messages with high throughput. It will consume CPU to put messages from and in batch, but manually you will need to do the same basically...

**Comment by tvoinarovskyi** [comment]
You can use a bit more efficient way to do that if you use `getmany()`:
```python
consumer = AIOKafkaConsumer(bootstrap_servers=consuming_cluster_servers)
producer = AIOKafkaProducer(bootstrap_servers=producing_cluster_servers)
consumer.subscribe(["topic1", "topic2"])

while True:
    mgsset = consumer.getmany(timeout_ms=1000)
    futs = []
    for tp, msgs in msgset.items():
        for msg in msgs:
            fut = await producer.send(value=msg.value, key=msg.key, timestamp=msg.timestamp)
            futs.append(fut)
    if futs:
        # This is basically where you will wait for the batch to be sent.
        await asyncio.gather(futs)
```

**Comment by shargan** [comment]
That's an accurate description of my essential use case. Like most use-cases, it's very simplified (for example, I'm fetching from many topics and many consumers, routing varies by topic, acceptance policies vary per destination, and so on).

What you've described above is an improvement on awaiting each send_and_wait and similar to how I'm currently doing it (the send_and_wait example I gave above was a simplified explanation of my current logic). There are a few inefficiencies at work that make this less than ideal.

First, it offers no fine batch control. I can make educated guesses at how full a batch is and try to stop filling it up at that point to ensure optimum throughput for my requirements, but those are invariably guesswork. If I overfill by a single message, my client pauses as both batches are drained and sent in sequence.

Second, each singular call to `await producer.send(...)` involves at least three cycles of the main event loop:
- The initial yield back (`await producer.send(...)`)
- The call to `self.client._wait_on_metadata(topic)` to ensure partition selection acts on accurate information
- The call to `self._message_accumulator.add_message(...)`
_ If the batch is full, at least two more in the form of `asyncio.wait(...)` followed by a recursive `add_message(...)`

Third, this still results in a 1:1 Message to Future ratio. The load of creating those objects and traversing the lists caps scalability by batch size (details below).

For the vast majority of use-cases, none of this is a big deal. With the data rates I'm working with, the number of topics/partitions, the number of different producers, and the additional background work happening in my application, these additional details begin to matter.

Even in a tight loop, this difference is visible. Here's what I'm using to benchmark:
```python
import asyncio
import random
import sys


async def bench_simple(num, payload, loop):
    from aiokafka import AIOKafkaProducer
    producer = AIOKafkaProducer(loop=loop)
    await producer.start()
    for _ in range(num):
        await producer.send("test", payload)
    await producer.stop()


async def bench_batch(num, payload, loop):
    from aiokafka.producer import AIOKafkaBaseProducer
    from aiokafka.structs import TopicPartition
    producer = AIOKafkaBaseProducer(loop=loop)
    await producer.start()

    partitions = await producer.partitions_for("test")
    part = random.choice(tuple(partitions))
    batch = producer.create_batch(TopicPartition("test", part))

    i = 0
    while i < num:
        fut = batch.append(None, payload)
        if fut is None:
            await producer.send_batch_and_wait(batch)
            partitions = await producer.partitions_for("test")
            part = random.choice(tuple(partitions))
            batch = producer.create_batch(TopicPartition("test", part))
            continue
        i += 1
    await producer.send_batch_and_wait(batch)
    await producer.stop()


def main(arg):
    num = 1000000
    size = 100
    payload = ("m" * size).encode()

    bench = bench_simple if arg == "simple" else bench_batch
    loop = asyncio.get_event_loop()
    start = loop.time()
    loop.run_until_complete(bench(num, payload, loop))
    loop.close()
    delta = loop.time() - start
    print("%d messages in %.2fs (%.2f msg/s)" % (num, delta, num / delta))

if __name__ == "__main__":
    main(sys.argv[1])
```

And here's the comparison:
```
(.venv) aiokafka (master)$ python bench_produce.py simple
1000000 messages in 40.68s (24584.40 msg/s)
(.venv) aiokafka (master)$ git checkout shargan/flex-producer
Switched to branch 'shargan/flex-producer'
(.venv) aiokafka (shargan/flex-producer)$ python bench_produce.py batch
1000000 messages in 25.58s (39089.51 msg/s)
```

To demonstrate the batch-size scaling, here are the results with quadruple the default batch size (65536):
```
(.venv) aiokafka (master)$ python bench_produce.py simple
1000000 messages in 39.50s (25314.29 msg/s)
(.venv) aiokafka (master)$ git checkout shargan/flex-producer
Switched to branch 'shargan/flex-producer'
(.venv) aiokafka (shargan/flex-producer)$ python bench_produce.py batch
1000000 messages in 19.07s (52446.19 msg/s)
```

**Comment by tvoinarovskyi** [comment]
> First, it offers no fine batch control. I can make educated guesses at how full a batch is and try to stop filling it up at that point to ensure optimum throughput for my requirements, but those are invariably guesswork. If I overfill by a single message, my client pauses as both batches are drained and sent in sequence.

That assumption is not correct, when a batch is full it is sent right away and a new one is created. Only if 2 batches are full will the call to `send()` wait. I don't get why you are bothered by when the batch is sent, you can control the throughput using `linger_ms` and `batch_size`.

> Second, each singular call to await producer.send(...) involves at least three cycles of the main event loop
It does not matter how many as long as there's no IO happening there. It's not really that big of CPU usage. You can try `uvloop` to get that to even less difference.

> Third, this still results in a 1:1 Message to Future ratio. The load of creating those objects and traversing the lists caps scalability by batch size (details below).

It's created for each message even in your case...

I'll see why your benchmark is showing such a difference and get back to you.

**Comment by shargan** [comment]
>> Third, this still results in a 1:1 Message to Future ratio. The load of creating those objects and traversing the lists caps scalability by batch size (details below).
>
> It's created for each message even in your case...
>
> I'll see why your benchmark is showing such a difference and get back to you.

In the PR I sent, batch.append() returns the same batch.future delivery Future for every message unless append(future=True). AIOKafkaProducer.send() sets that kwarg for the sake of API consistency. If I set it to False in the simple benchmarks, I see a modest but solid increase in throughput:

```
1000000 messages in 35.00s (28569.97 msg/s)
```

I believe most of the rest of the improvement comes from avoiding 3+ coroutine switches per message submission, avoiding a log.debug call, and a bit from avoiding calls to _serialize, _partition, and a handful of other per-send methods under the hood.

>> If I overfill by a single message, my client pauses as both batches are drained and sent in sequence.
>
> That assumption is not correct, when a batch is full it is sent right away and a new one is created.

Recall that I was referring to the code example you gave where the client was yielding back to asyncio.gather() to await delivery of all the messages in question. That will not finish until both batches are acked by the broker.

> Only if 2 batches are full will the call to send() wait.

I'm confused by this. Reading MessageAccumulator.add_message(), it looks like it's always going to consider self._batches[-1] the "active" batch (I assumed that was to support reenqueue without accidentally adding messages to it or blocking send() unnecessarily).

If that active batch is full (batch.append() returns None on line 219), then add_message yields back to the IOLoop until it's drained by _sender_routine (lines 224-225) and then recursively schedules addition of the message again (lines 229-230). While this may not wait for long, it does wait.

Am I misunderstanding?

> It does not matter how many as long as there's no IO happening there.

Not in this tight use case, no. But again, my application is doing a lot more than just generating and sending messages. The same loop is being used for multiple consumers, sending to many different topics/nodes/clusters, for inter-cluster signaling, monitoring ZK configuration nodes, etc. There's simply a lot more tasks to go through on each event loop cycle.

**Comment by tvoinarovskyi** [comment]
> If that active batch is full (batch.append() returns None on line 219), then add_message yields back to the IOLoop until it's drained by _sender_routine (lines 224-225) and then recursively schedules addition of the message again (lines 229-230). While this may not wait for long, it does wait.
Am I misunderstanding?

No, but there's a difference there, as it only waits for the batch to be sent (it should happen on next loop turn, so it's very fast), and does not wait for ACK on broker side.

In a tight loop, like in the benchmark, it does not do much difference thou, expected at least some... Maybe a bug there will try to dig it.

**Comment by shargan** [comment]
(for the sake of posterity: took this conversation to Gitter and agreed to put together a minimally invasive batch interface. We can iterate on the details once it's in place.)

**Comment by shargan** [comment]
Lighter-weight version in https://github.com/aio-libs/aiokafka/pull/217. Benchmarks remain fairly stable:

```
(.venv) aiokafka (shargan/batch-producer)$ python bench_produce.py simple
1000000 messages in 40.21s (24870.41 msg/s)
(.venv) aiokafka (shargan/batch-producer)$ python bench_produce.py batch
1000000 messages in 26.09s (38326.24 msg/s)

# original PR
# (.venv) aiokafka (shargan/flex-producer)$ python bench_produce.py batch
# 1000000 messages in 25.58s (39089.51 msg/s)
```

**Comment by tvoinarovskyi** [comment]
#217 is merged, but not closing as @shargan promised to update the docs )

**Comment by shargan** [comment]
Docs updated in https://github.com/aio-libs/aiokafka/pull/241

**Comment by tvoinarovskyi** [comment]
Should be ok to close this.
