### ISSUE TITLE
Consumer no longer able to pause and resume topic partitions

### ISSUE THREAD

**Issue by vineetgoel** [aio-libs/aiokafka#304]
Did `aiokafka==0.4.0` remove the ability to `pause` and `resume` topic partitions for consumption? Is there a way of doing this in the new version of aiokafka?

@TarasLevelUp

**Comment by vineet-rh** [comment]
Currently we were using the `subscription_state` from `kafka-python` to pause and resume as follows:

```
consumer._subscription.pause(partition=tp)
consumer._subscription.resume(partition=tp)
```

Doesn't look like thats possible with the new aiokafka subscription state class.

**Comment by tvoinarovskyi** [comment]
That was never intended API, nor was it documented... You should pass partitions you want to consume on each getmany/getone call to pause. If it's a problem, I am open for suggestions

**Comment by ask** [comment]
Wouldn't we then have to wait for the currently running getmany to complete before pausing? or throw away records we receive while it's paused.  I'm not sure, but it's maybe better to have this implemented at a lower level, AFAICT the code is not far from supporting that, unless there is something with the new "immutability" that means it's more difficult.

Thanks for the new version of aiokafka btw! Lots of great changes, and seeing a nice speed up as well.  I think you're going to be interested in seeing what we have built on top of it :D

**Comment by ask** [comment]
@vineet-rh Reading the kafka-python and aiokafka code now btw, I wonder if we are not possibly throwing away messages when we pause? https://github.com/aio-libs/aiokafka/blob/v0.3.0/aiokafka/fetcher.py#L378-L381

Does this mean we have to seek back to the previous offset before resuming?

**Comment by ask** [comment]
Apropos upgrading to 0.4.0, these new isinstance checks are a bit annoying to us since they break duck typing.

We use static typing and to make the Kafka client abstract we've had to define our own TopicPartition class that we use for typing:  whenever we get a aiokafka.TopicPartition we just cast it to our type: ```return cast(OurTopicPartition, tp)```, no actual converting or copying needed.

But with the new isinstance checks we've had to explicitly convert all of them on every call, so
would it be possible to if not remove them, at least make it possible for us to override how they work?

Maybe by having a `self._verify_is_topic_partition_list(partitions)` or something and then we could override that.  Guess I should just submit a pull request.

**Comment by vineet-rh** [comment]
Ahh interesting idea @TarasLevelUp

**Comment by ask** [comment]
@tvoinarovskyi I fixed pausing/resuming by using  getmany as you suggested.  Thanks!

Shouldn't Consumer.getmany pass `*partitions` to `Fetcher.fetched_records` as `set(partitions)`? It seems to be using it as a set (e.g. `tp in active_partitions`.

**Comment by tvoinarovskyi** [comment]
@ask
> Apropos upgrading to 0.4.0, these new isinstance checks are a bit annoying to us since they break duck typing.

Ok, understand the issue here. We can change to duck typing for those checks, no problem. PR welcome)

**Comment by tvoinarovskyi** [comment]
@ask

> Does this mean we have to seek back to the previous offset before resuming?

No, you don't have to seek. But the messages are thrown away, there is no way to avoid that. The difference is, that the thrown away messages will be required again when the partition is resumed.

> Wouldn't we then have to wait for the currently running getmany to complete before pausing? or throw away records we receive while it's paused. I'm not sure, but it's maybe better to have this implemented at a lower level, AFAICT the code is not far from supporting that, unless there is something with the new "immutability" mentioned that means it's more difficult?

Yea, that is an issue actually. Did not think of such a use case, I mean in 1 threaded `kafka-python` case you would not be able to do that too) So you want something like:

```python
fetch_task = loop.create_task(consumer.getmany())
await asyncio.sleep(0.1)
consumer.pause(tp1)
msgs = await fetch_task
```

And for `msgs` to have `tp1` omitted. We could return the `pause/resume` API as in `kafka-python`, would that be ok?

The `getmany(*partitions)` API we got from a use case where we spawned a task per each partition in `ConsumerRebalanceListener` that only consumed its part. After that, we kinda removed `pause/resume`, as did not see any need for it.
