### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by TarasLevelUp** [aio-libs/aiokafka#32]

**Comment by Drizzt1991** [comment]
The kerberos will require a lot more work. If needed should be another issue.
As for SSL, the implementation is quite simple, but how should we test SSL support? We have docker too, so probably it should be upgraded to support ssl.

**Comment by popravich** [comment]
If you only need a ssl proxy, you can try something like this: https://github.com/aio-libs/aioredis/commit/cd3c0eb2b50c99ecf66dd94150d339cf161f9854

**Comment by Drizzt1991** [comment]
fixed by #81 SASL will be in a different issue
