### ISSUE TITLE
Relax kafka-python dependency version

### ISSUE THREAD

**Issue by Gr1N** [aio-libs/aiokafka#325]
Hi,

Why `kafka-python` dependency pinned to the `1.3.5` version? Can we relax version and define in `setup.py` with `>=1.3.5`?

Thanks

**Comment by tvoinarovskyi** [comment]
Because we still use some of `kafka-python`
s internals (protocol, errors, etc.), which change and versions are not compatible 100%.

**Comment by tvoinarovskyi** [comment]
What problem do you have with this? Describe your use case, maybe it's possible to avoid the issue to some degree.

**Comment by Gr1N** [comment]
I'm just curious. We have checkers for outdated packages and `kafka-python` always marked as outdated. Thank for the answer.

**Comment by tvoinarovskyi** [comment]
Closing this, if you don't mind. I do plan to remove the dependency in the future, but probably for 1.0.0 release, as it will be an incompatible change.

**Comment by alexjg** [comment]
I know this is closed but I think this is the right place to ask this question. I'm running into a bug in version 1.3.5 of kafka-python so I want to try upgrading the dependency. Are there any particular breaking changes I should be aware of?
