### ISSUE TITLE
API version config is utterly broken

### ISSUE THREAD

**Issue by tvoinarovskyi** [aio-libs/aiokafka#334]
As I can see from the code, at some point we broke the `api_version` config. It does not support `0.11`+ brokers, specifying anything other than `auto` will just degrade to `0.9` because of type bug...
So we need to:
* Add a normal API version field parser, allowing to specify proper versions
* Allow specifying minor versions, as there are differences between `0.10` minor versions, that do matter
* Add a normal <= validator to disallow older versions

**Comment by asvetlov** [comment]
`distutils.version.StrictVersion`?

**Comment by tvoinarovskyi** [comment]
Semantics are very similar... Why not )

**Comment by tvoinarovskyi** [comment]
`StrictVersion('0.11.1').version`
