### ISSUE TITLE
Assertion failed in Subscription State

### ISSUE THREAD

**Issue by vineetgoel** [aio-libs/aiokafka#349]
I saw this assertion failing in production. Wondering how this may happen and if there is anything we should do to prevent this:

https://github.com/aio-libs/aiokafka/blob/v0.4.0/aiokafka/consumer/subscription_state.py#L492

**Comment by tvoinarovskyi** [comment]
@vineetgoel That is your private repository. No way for me to read it)

**Comment by tvoinarovskyi** [comment]
Omg)
```python

            # There could have been a seek() call of some sort while
            # waiting for committed point
            if tp_state.has_valid_position or tp_state.awaiting_reset:
                continue
```
The 2nd condition is inversed. Grr, and coverage was full falsly, cause we don't cound branching(

**Comment by tvoinarovskyi** [comment]
You are not calling aiokafka from several threads, are you? I looked through the code, did not find any way to hit that assert...

**Comment by vineetgoel** [comment]
It should ideally not be happening from different threads unless unexpectedly.

**Comment by tvoinarovskyi** [comment]
Tried several times to search for a way, but still, the only possibility would be to run several threads or change something internal.  Will close the issue if you have any way to reproduce it, or you will see it again in aiokafka>=0.5, feel free to open a new issue.
