### ISSUE TITLE
Upgrade kafka-python version for https://github.com/dpkp/kafka-python/pull/1312

### ISSUE THREAD

**Issue by czchen** [aio-libs/aiokafka#366]
There is a [bug](https://github.com/dpkp/kafka-python/pull/1312) in kafka-python which was fixed in version `1.4.0`. It could be great if aiokafka can update dependency to avoid this bug.

**Comment by tvoinarovskyi** [comment]
Can you reproduce the bug in aiokafka? As far as I know, aiokafka uses asyncio's IP resolution, which should not have the DNS issues. Could you help me reproduce it?

**Comment by tvoinarovskyi** [comment]
Anywhat the dependency was updated. Thanks for the concern!
