### ISSUE TITLE
Python 3.7 support: kafka-python >= 1.4.3 required

### ISSUE THREAD

**Issue by mikmatko** [aio-libs/aiokafka#369]
`async` is a reserved keyword in Python 3.7. This was not properly handled in kafka-python versions prior to 1.4.3. In order to support Python 3.7 in aiokafka, kafka-python version must be updated to >= 1.4.3

**Comment by Gr1N** [comment]
Hi! Any updates on this? @tvoinarovskyi @webknjaz

**Comment by Gr1N** [comment]
Tried to fix and this is not simple without knowledge how library works. Main problem in `ProducerRequest_v0`: messages type changed from `MessageSet` to `Bytes` https://github.com/dpkp/kafka-python/blob/master/kafka/protocol/produce.py#L100.

**Comment by Gr1N** [comment]
But maybe there are another problem, some of tests (e.g. `TestConsumerIntegration.test_consumer_position`) failing with `TimeoutError`.

**Comment by jettify** [comment]
Thanks for looking into this, we need help from @tvoinarovskyi at least to debug an issue.

**Comment by mikmatko** [comment]
@tvoinarovskyi Would you mind taking a look at this. I can see that there's a branch [v0.5](https://github.com/aio-libs/aiokafka/tree/v0.5) where you had updated kafka-python version to 1.4.1 a few months ago in [this pr](https://github.com/aio-libs/aiokafka/pull/319), so I'm guessing you might have something to say about this issue :)

Thanks!

**Comment by tvoinarovskyi** [comment]
@mikmatko @Gr1N Will take a look this weekend. Should not be too troublesome

**Comment by Gr1N** [comment]
Awesome! Thank you!

**Comment by tvoinarovskyi** [comment]
@mikmatko  Yea, I kind of already had it fixed, but never finished v2 protocol. Backported some changes, will have to force 0.5 to happen soon, so this will not happen again.

**Comment by Gr1N** [comment]
@tvoinarovskyi when you're planning to release a new version of package?

**Comment by tvoinarovskyi** [comment]
I need to fix a large problem first. Either this or next week. Push me if I do not)

**Comment by Gr1N** [comment]
k :)

**Comment by tvoinarovskyi** [comment]
Mainly #344 its a bad one(

**Comment by tvoinarovskyi** [comment]
@Gr1N done, btw =)

**Comment by Gr1N** [comment]
Many thanks!

**Comment by discosultan** [comment]
Why was the version pinned to `==1.4.3` instead of `>=1.4.3` (or possibly `>=1.4.3,<2.0.0` when thinking of semver backward compatibility guarantees)?

https://github.com/aio-libs/aiokafka/blob/2e59514d19e2a9819338e1f796079395f89460e2/setup.py#L92

**Comment by tvoinarovskyi** [comment]
@discosultan Because we use a lot of kafka-python internals. You can ask PIP to install different versions if you are sure it will work for you.
kafka-python is developing and breaking internals even between minor versions.
What problems does that impose for your case?

**Comment by discosultan** [comment]
@tvoinarovskyi No problems really, just a curiosity. Thanks for the info!
