### ISSUE TITLE
Coordinator heartbeat spamming with Heartbeat session expired

### ISSUE THREAD

**Issue by Artimi** [aio-libs/aiokafka#372]
Using `aiokafka==0.4.1`, `kafka==0.9.0`. This tasks comes from https://github.com/aio-libs/aiokafka/issues/335#issuecomment-392542928.  When I unsubscribe from all topic partitions heartbeat task is still running and complaining and spamming errors:
```
May 29th 2018, 17:36:24.473 INFO Unsubscribed all topics or patterns and assigned partitions
May 29th 2018, 17:36:53.581 error Heartbeat session expired - marking coordinator dead
May 29th 2018, 17:36:53.685 error Heartbeat session expired - marking coordinator dead
May 29th 2018, 17:36:54.027 error Heartbeat session expired - marking coordinator dead
May 29th 2018, 17:36:54.131 error Heartbeat session expired - marking coordinator dead
```
Then this happens every ~150-300 ms until I kill the application. I'm not sure if this will recover when I subscribe new topics.

I was looking to the code and when you call `consumer.unsubscribe()` it calls `GroupCoordinator.maybe_leave_group()` which subsequently calls `GroupCoordinator.reset_generation()` which should perform `GroupCoordinator._stop_heartbeat_task()` in `GroupCoordinator._coordinator_routine()`. However after this rejoin is performed and I'm not sure if it succeeds even with no subscription.

What should be done to prevent this behavior? Should be the heartbeat task stopped until we have some subscriptions?

**Comment by tvoinarovskyi** [comment]
By all means, leaving the group should stop the heartbeat. If it did not it's a bug.
