### ISSUE TITLE
Old pyup PRs are not closing

### ISSUE THREAD

**Issue by rooterkyberian** [aio-libs/aiokafka#391]
Outdated pyup PRs should be closed it automatically, not sure why they aren't.

https://pyup.io/docs/bot/config/#close-stale-prs

PRs that should have been closed:
https://github.com/aio-libs/aiokafka/pull/346
https://github.com/aio-libs/aiokafka/pull/347
https://github.com/aio-libs/aiokafka/pull/357

Personally I would suggest setting `schedule` to every month or two weeks, as it can get quite chatty as you see making human contributions less visible.

**Comment by tvoinarovskyi** [comment]
Done
