### ISSUE TITLE
Manual partition consuming is broken

### ISSUE THREAD

**Issue by nemosupremo** [aio-libs/aiokafka#394]
It doesn't look like you can use Manual Partition Consuming without hitting an assert:

```
Application error
Traceback (most recent call last):
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/grpclib/server.py", line 312, in request_handler
    await method.func(stream)
  File "./client-python/main.py", line 85, in Start
    await self.consumer.start()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiokafka/consumer/consumer.py", line 270, in start
    self._coordinator.assign_all_partitions(check_unknown=True)
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiokafka/consumer/group_coordinator.py", line 103, in assign_all_partitions
    self._subscription.assign_from_subscribed(partitions)
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiokafka/consumer/subscription_state.py", line 202, in assign_from_subscribed
    SubscriptionType.AUTO_PATTERN, SubscriptionType.AUTO_TOPICS]
```

Basically `start` triggers an asset that the SubscriptionType is either `SubscriptionType.AUTO_PATTERN, SubscriptionType.AUTO_TOPICS`

## Reproduction

```python
consumer = AIOKafkaConsumer(
            loop=self.loop,
            bootstrap_servers=request.kafka_brokers,
            enable_auto_commit=False,
            group_id=None,
        )
consumer.assign(TopicPartition('foo', 0))
await consumer.start()
```

## Cause

When you call `consumer.assign` that sets changes the `consumer`'s [subscription to ManualSubscription](https://github.com/aio-libs/aiokafka/blob/9659b380c9a28923fe3ae3137784dff411686dfe/aiokafka/consumer/subscription_state.py#L169) with a subscription type of `SubscriptionType.USER_ASSIGNED`.

```python
def assign_from_user(self, partitions: Set[TopicPartition]):
        """ Manually assign partitions. After this call automatic assignment
        will be impossible and will raise an ``IllegalStateError``.
        Caller: Consumer.
        Affects: SubscriptionState.subscription
        """
        self._set_subscription_type(SubscriptionType.USER_ASSIGNED)

        self._change_subscription(
            ManualSubscription(partitions, loop=self._loop))
        self._notify_assignment_waiters()
```

Next, when you call `consumer.start` we then check if `consumer.subscription` is not `None`, and then call `NoGroupCoordinator .assign_all_partitions`.

```python
self._coordinator = NoGroupCoordinator(
    self._client, self._subscription, loop=self._loop,
    exclude_internal_topics=self._exclude_internal_topics)

# If we passed `topics` to constructor.
if self._subscription.subscription is not None:
    yield from self._client.force_metadata_update()
    self._coordinator.assign_all_partitions(check_unknown=True)
```

Which then calls the base class `Subscription` `assign_from_subscribed`:

```python
def assign_from_subscribed(self, assignment: Set[TopicPartition]):
        """ Set assignment if automatic assignment is used.
        Caller: Coordinator
        Affects: SubscriptionState.subscription.assignment
        """
        assert self._subscription_type in [
            SubscriptionType.AUTO_PATTERN, SubscriptionType.AUTO_TOPICS]

        self._subscription._assign(assignment)
        self._notify_assignment_waiters()
```

Which calls the assert. My hunch is that the assert should also include `SubscriptionType.USER_ASSIGNED`, however does adding that to the assert break any invariants required by `_assign` and `_notify_assignment_waiters`?

**Comment by nemosupremo** [comment]
Running with `PYTHONOPTIMIZED=1` (and therefore disabling asserts) and consumption works fine.

**Comment by nemosupremo** [comment]
Coming across another issue where `NoGroupCoordinator` presumes that all partition should be consumed. For example if you only wish to manually manage partitioning, and you assign part of the partitions to a consumer, you hit

```
  File "/usr/local/lib/python3.6/site-packages/aiokafka/consumer/group_coordinator.py", line 109, in assign_all_partitions
    tp_state.reset_committed(
AttributeError: 'NoneType' object has no attribute 'reset_committed'
```

It seems NoGroupConsumer tries to `assign_all_partitions` even though you have only requested a partial set.

**Comment by tvoinarovskyi** [comment]
Hmm, ok now this one is bad) the code should probably handle it differently. Manual subscription should never call assign_from_subscribed. That was the idea of that assert. Proves that the coverage is yet missing several scenarious.
