### ISSUE TITLE
Consumer/Producer cannot recover from NodeNotReadyError

### ISSUE THREAD

**Issue by vineetgoel** [aio-libs/aiokafka#399]
I am noticing that if a broker becomes unresponsive for sometime or dies (after a a slightly long period of non-responsiveness), aiokafka consumers can not recover from it i.e. the consumer thread (asyncio) gets stuck. Is this a known issue or fixed in recent versions?

I am on 0.4.0.

**Comment by Achillesxu** [comment]
@tvoinarovskyi: if a broker becomes unresponsive for sometime or dies, i use getmany(timeout_ms=1000, max_records=5), the function always did not  get any message, and i must restart program to start read message from kafka

**Comment by tvoinarovskyi** [comment]
Ok, probably it may relate to #344, but without any exception or logs to work with, this is hard to guarantee. I plan to do a 0.4.2 this week, please try it, should be fixed.

**Comment by tvoinarovskyi** [comment]
The related problem should be solved in #344, will close this.
