### ISSUE TITLE
Heartbeat failed for group <id> because it is rebalancing

### ISSUE THREAD

**Issue by kumarbalap** [aio-libs/aiokafka#406]
Hi,

Our node details are as follows
Kafka - 3 nodes (shared between different applications)
App - 2 nodes (ie 2 consumers per topic, total 5 topics)
Kafka settings - version 1.0 with default settings, nothing changed

FYI, Kafka settings

```
broker.id=1
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=/var/lib/kafka
num.partitions=1
num.recovery.threads.per.data.dir=1
default.replication.factor=3
offsets.topic.replication.factor=3
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=2
log.retention.bytes=1073741824
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
log.retention.hours=120
zookeeper.connection.timeout.ms=6000
confluent.support.metrics.enable=false
group.initial.rebalance.delay.ms=0
confluent.support.customer.id=anonymous
auto.create.topics.enable=false
```

Consumer s running fine , if I run one node with one consumer. The moment I start another consumer from other node, I get the group rebalancing error for some topics immediately.

I have tried with below consumer settings, still I see the same error.

```
AIOKafkaConsumer(
        #evgaKafkaName(topic_name),
        topic_name,
        loop=loop,
        #bootstrap_servers=getKafkaBrokers(),
        bootstrap_servers=BROKERS,
        # group_id=evgaKafkaName(group_name),
        group_id=group_name,
        #security_protocol='SSL',
        #ssl_context=getKafkaSslContext(),
        value_deserializer=lambda v: v.decode('utf8'),
        #value_deserializer=deserializer,
        enable_auto_commit=True,
        auto_offset_reset=auto_offset_reset,
        consumer_timeout_ms=consumer_timeout_ms,
        retry_backoff_ms=10,
        #heartbeat_interval_ms=50,
        session_timeout_ms=60000,
        #request_timeout_ms=80 * 1000,
        #fetch_max_wait_ms=3000,
        max_poll_records=50
    )
```

What could be the issue, anything to do with rebalance.max.retries and rebalance.backoff.ms and session timeout ?

Thanks,
Bala

**Comment by vineetgoel** [comment]
Do you use the default consumer group coordinator or have your over-written it to write out Partition Assignment, and group coordination?

**Comment by kumarbalap** [comment]
No, I have tried with many different group names, still the same error.

**Comment by vineetgoel** [comment]
In the ideal case, this should only happen if there is something blocking in the code processing the kafka messages. This error is typically thrown if there the kafka consumer times out while rebalance.

**Comment by kumarbalap** [comment]
I have increased the session timeout and reduced the max poll records rate, but I still see the same error.
FYI,
If I run with single consumer it runs for a while, then I get the below partition error.
```
OffsetCommit failed for group se_grp_personid_sf_evga on partition TopicPartition(topic='se.person.sf.evga', partition=0) with offset OffsetAndMetadata(offset=53, metadata=''): RequestTimedOutError
OffsetCommit failed for group se_grp_personid_sf_evga on partition TopicPartition(topic='se.person.sf.evga', partition=1) with offset OffsetAndMetadata(offset=53, metadata=''): RequestTimedOutError
Auto offset commit failed: [Error 7] RequestTimedOutError
```

If I try with one more consumer, then I get the rebalance error immediately.

**Comment by tvoinarovskyi** [comment]
Probably relates to #335

**Comment by yasirk** [comment]
Hi, i'm seeing the same error message on Kafka 2.1.0 and its crashing the group coordinator. This only happens for one topic that has several consumer groups that are running on kubernets. Any pointers on how to fix this?

**Comment by pod2metra** [comment]
@yasirk Look's like, We catch the same problem.

**Comment by tvoinarovskyi** [comment]
@pod2metra Are you are seeing errors of similar kind in logs, or are you having problems with consuming messages because of it constantly happening?

If it's just some messages in logs, that's OK. It's how Kafka behaves (at least used to before they introduced some optimizations, which are not implemented in aiokafka sadly). When Kafka broker sees some members of the group leave or timeout it will throw an error to all remaining participants. Usually, this error will be seen on the next heartbeat, which will result in a log message similar to:
``` Heartbeat failed for group <id> because it is rebalancing
```

If you have a different case, please open a new issue. Sorry for the trouble.
