### ISSUE TITLE
consumer with group id fires many coordination_error_fut and will not exit

### ISSUE THREAD

**Issue by doseeing** [aio-libs/aiokafka#436]
https://github.com/aio-libs/aiokafka/commit/1f417f37873fb7951528bd67a3368c6da4b36fe6 causes consumer with group id parameter creating many coordination_error_fut coroutines and will not exit. This will use more and more memory.
Environment: Python3.6

**Comment by tvoinarovskyi** [comment]
Did you see that actually happen? From what I know of the coroutines, as long as we don't store the reference it will just clear them with normal GC. Moreover, coordination_error_fut  is not a coroutine, but a simple future, so it's even less of an issue. Do you have a way to reproduce the issue? Maybe there are some warnings in the logs?

**Comment by tvoinarovskyi** [comment]
Sorry for the long wait. Thanks, was able to confirm this very fast.

**Comment by tvoinarovskyi** [comment]
Will get a 0.4.3 fix asap

**Comment by tvoinarovskyi** [comment]
Pushed 0.4.3 with a fix, please try it.
