### ISSUE TITLE
Please support consumer and producer sharing a client object(connection pool)

### ISSUE THREAD

**Issue by wencan** [aio-libs/aiokafka#438]
Please support consumer and producer sharing a client object(connection pool).

**Comment by tvoinarovskyi** [comment]
Current implementation of Consumer protocol expects blocking the socket channel on Fetch. If we try to produce and consume using the same client they will fight for the socket, yielding bad performance. If we split sockets we will not get much bennefit from sharing the client.
What usecase do you want to solve by sharing Consumer and Producer?

**Comment by tvoinarovskyi** [comment]
Sorry, but I will close the issue due to no answer for now. I don't see much benefit of having a shared client as of now, please feel free to open a new issue if you see a benefit of sharing. I am opened for discussion.
