### ISSUE TITLE
Producer sends metadata requests about all topics on kafka broker

### ISSUE THREAD

**Issue by ulrikjohansson** [aio-libs/aiokafka#440]
We've recently started using ACLs for our Kafka cluster, and we're seeing lots of spam in our kafka logs about aiokafka trying to get metadata for all topics, and being denied because of these ACLs.

Everything seems to be working fine, it just seems unnecessary to try and get metadata for stuff the producer can't access anyway.

I think I've found a workaround for now, which is to set the topic the producer is supposed to use with `producer.client.set_topics([<topic>])` before starting the producer with `start()`, but I'm not 100% certain this will not cause any side effects.

Is this a safe thing to do in order to get rid of all the ACL spam in our kafka logs?

Update: seems related to #287

**Comment by tvoinarovskyi** [comment]
Yes that problem is present, thanks for the report. The fix provided seems sensible to me, can't think of any problems with it.
