### ISSUE TITLE
memory leak in consumer

### ISSUE THREAD

**Issue by MainRo** [aio-libs/aiokafka#444]
The fix of issue #294 caused a memory leak on each record read from a consumer.

It seems there are two reasons for this leak. The first one is the fact that _coordination_error_fut_ is never cancelled after the wait, so it is never removed from the pending tasks of the asyncio event loop. The following changes should fix this issue:

```python
    @asyncio.coroutine
    def _wait_for_data_or_error(self, coro):
        if self._group_id is None:
            return (yield from coro)
        else:
            coordination_error_fut = self._coordinator.error_future
            data_task = ensure_future(coro, loop=self._loop)
            done, pending = yield from asyncio.wait(
                [data_task, coordination_error_fut],
                return_when=asyncio.FIRST_COMPLETED)

            pending.pop().cancel()
            return done.pop().result()
```

With these changes, the (unique) pending future is cancelled, and the (unique) done future's result is returned. So the result of future that completed is returned and the other one is cancelled.

The second reason of the leak is due to the shield function of asyncio that never removes completion callbacks of the inner future when the outer future is cancelled. I filled an issue for that here:
https://bugs.python.org/issue35125

With these two changes, the memory consumption of a consumer seems stable on 0.4.2.

**Comment by tvoinarovskyi** [comment]
Related to #436

**Comment by tvoinarovskyi** [comment]
@MainRo Hmm, never thought about the second one. It will certainly cause some trouble. Ok, as we still use `wait()` call here, we can just remove the shield, as it will be blocked from cancellation by wait.

**Comment by tvoinarovskyi** [comment]
@MainRo Pushed 0.4.3 with this fix. Please try it.

**Comment by MainRo** [comment]
Thanks, it works well.
