### ISSUE TITLE
can't reconnect if brokers go down and bootstrap servers change IP

### ISSUE THREAD

**Issue by dedsm** [aio-libs/aiokafka#456]
if the brokers go down and the bootstrap servers change IP (a kubernetes kafka deployment deleted and re-applied triggers this) then the client will keep trying to connect to the old bootstrap server IPs and never try to resolve the DNS again, I fixed it by monkeypatching `force_metadata_update` to call bootstrap and `on_connection_closed` to call `_wait_on_metadata` which in turn forces the update of the metadata  to always re-bootstrap in case of disconnection, but I think it's not the best way to do it, I guess it bootstraps too often with this code, does the trick though.

```python
_force_metadata_update = AIOKafkaClient.force_metadata_update


def force_metadata_update(client):
    asyncio.shield(client.bootstrap())
    return _force_metadata_update(client)


AIOKafkaClient.force_metadata_update = force_metadata_update

_on_connection_closed = AIOKafkaClient._on_connection_closed


def on_connection_closed(client, conn, reason):
    if (
        reason in [
            CloseReason.CONNECTION_BROKEN, CloseReason.CONNECTION_TIMEOUT
        ]
    ):
        asyncio.shield(client._wait_on_metadata())

    _on_connection_closed(client, conn, reason)


AIOKafkaClient._on_connection_closed = on_connection_closed
```

**Comment by tvoinarovskyi** [comment]
What host is configured on the broker side as `advertised_host`? Is it the dns of the server, or is it the IP. The advertised_listener should point to host, not IP address. 

Bootstrap is the process of resolving the initial cluster setup, it is not ment to be used later on. Every node in cluster setup is identified by an ID, the code does not operate on IP addresses. The only case where you will not be able to reconnect is if every node changes the IP address and client can't refresh metadata. But I think the host fix should be enough.

**Comment by dedsm** [comment]
huh now I see, the helm chart I was using used the IPs as advertised listeners, setting the DNS manually in the advertised listeners works. I still wouldn't mind to have a failsafe in case of IP only, like fail after a while or something else than keep running forever. But feel free to close the issue as the main issue is solved by advertising DNS names.

Thanks!

**Comment by tvoinarovskyi** [comment]
Great, I will think about having a failsafe if all nodes in the cluster are not accessible for a long period of time or something similar. That makes sense. Sadly no such behaviour in Java client so will need to think carefully here. Will close this one.
