### ISSUE TITLE
API documentation is mostly empty

### ISSUE THREAD

**Issue by tjwalton** [aio-libs/aiokafka#466]
On https://aiokafka.readthedocs.io/en/stable/api.html, most of the sections are empty, for example "AIOKafkaProducer class".

Finding a different version of the documentation, for example https://aiokafka.readthedocs.io/en/new_docs/api.html, shows the arguments and docstrings of the various objects.

**Comment by tvoinarovskyi** [comment]
ooops. Probably something went wrong =)

**Comment by tvoinarovskyi** [comment]
Fixed it in the upstream. Will try to do a backport of the fix to that branch. Hope it will build properly )

**Comment by tvoinarovskyi** [comment]
For now use https://aiokafka.readthedocs.io/en/latest/api.html =) Hmm, we should probably publish all versions of the library documentation...

**Comment by tvoinarovskyi** [comment]
Well, it's not empty now)

**Comment by tvoinarovskyi** [comment]
Closing as the docs are fine now
