### ISSUE TITLE
connections_max_idle_ms default means 9 minutes not 9 hours

### ISSUE THREAD

**Issue by aoberegg** [aio-libs/aiokafka#491]
In the documentation it says: 

> connections_max_idle_ms (int) – Close idle connections after the number of milliseconds specified by this config. Specifying None will disable idle checks. Default: 540000 (9hours).

which basically means 9minutes not 9 hours if it's really in ms.

**Comment by tvoinarovskyi** [comment]
ooops. That's the same default as in Kafka for Java. It does mean 5mins, I just was dumb when writing the 9hours comment)
