### ISSUE TITLE
AIOKafkaConsumer and AIOKafkaProducer in the same coroutine?

### ISSUE THREAD

**Issue by cmollis** [aio-libs/aiokafka#500]
I have something that looks like this:
producer = AIOKafkaProducer(
        loop=loop, bootstrap_servers='<servers>')

    await producer.start()
    print("producer %d started" % idVal)

    consumer = AIOKafkaConsumer(
        'eai2-stream',
        loop=loop, bootstrap_servers='<servers>',
        group_id='eai2-consumer-group')

    await consumer.start()
    print("consumer %d started" % idVal)

    try:
        #consume some messages
        async for msg in consumer:
            print("consumed :", idVal, msg.topic, msg.partition, msg.offset, msg.key, msg.value, msg.timestamp)
            await producer.send("group-status-stream", msg.value)

This seems to work fine... but I'm wondering if it's ok to start the producer and consumer in the same coroutine..

**Comment by tvoinarovskyi** [comment]
Yes it should work just fine.

**Comment by cmollis** [comment]
Yes!.. thanks it actually does work well.  Sorry for not closing.  Thanks for your help.
