### ISSUE TITLE
Support later versions of kafka-python

### ISSUE THREAD

**Issue by bmoscon** [aio-libs/aiokafka#506]
Currently the version of kafka-python required is 1.4.3, which is nearly a year old. Are there plans to support later versions anytime in the near future? My interest is primarily in `KafkaAdminClient` that newer version of kafka-python expose. Even if the new class is not supported in aiokafka I could at least use it through kafka-python (which is what I'm trying to do).

**Comment by tvoinarovskyi** [comment]
Try to make a PR with the latest version) If it builds and tests pass - merge and release will follow.

**Comment by bmoscon** [comment]
@tvoinarovskyi done - thanks!

https://github.com/aio-libs/aiokafka/pull/508

**Comment by tvoinarovskyi** [comment]
Will try to figure out a release on the week, there are 2/3 things wanted to do for 0.6.0.

**Comment by bmoscon** [comment]
@tvoinarovskyi thanks!

**Comment by alexpirine** [comment]
Hi @tvoinarovskyi, any news? Could you please create a release with #508? This is blocking for us…

Any way we can help? Could we be project contributors?

**Comment by tvoinarovskyi** [comment]
@alexpirine Sorry wanted to fix 2 bugs on top but did not have any free time at all. Will do a release right now, it's not hard. 
As for the later, feel free to contribute, if the PR's will be sensible - we will add you as a contributor.

**Comment by tvoinarovskyi** [comment]
done
