### ISSUE TITLE
UnknownProducerId

### ISSUE THREAD

**Issue by DeoLeung** [aio-libs/aiokafka#510]
```bash
  File "/usr/local/lib/python3.7/site-packages/aiokafka/producer/producer.py", line 452, in send_and_wait
    return (yield from future)
aiokafka.errors.UnknownProducerId: [Error 59] UnknownProducerId
```

I ran into this issue and from [stackoverflow](https://stackoverflow.com/questions/51036351/kafka-unknown-producer-id-exception?rq=1) it says it shall get a new id.

How can I get a new id? should I recreate the `Producer` instance?

**Comment by tvoinarovskyi** [comment]
Hi, thanks for the report. Could you explain your use-case, do you have little traffic on that node? Also, could you share your producer configuration? 
I suspect that this changeset way not yet implemented in aiokafka, new bugs pop up in the upstream from time to time. Recreating the producer will definitely work, but I'm not sure if I don't know the exact use case.

**Comment by tvoinarovskyi** [comment]
Strangely I stumbled on this too with a very strange consequence of subsuquent restarts failing to start the Producer. After debugging it seems like Kafka goes into a mode, where it just returns CONCURRENT_TRANSACTIONS error for all InitPID requests from this transactional id.

**Comment by DeoLeung** [comment]
for my use case, it usually happens on my non-prod environment with very little traffic, I guess it's the retention setting(1day & 1GB). 

and I use kafka 2.1.1

**Comment by tvoinarovskyi** [comment]
Yea, that is basically what is described here https://stackoverflow.com/questions/51036351/kafka-unknown-producer-id-exception?rq=1. It should yet be fixed by kafka broker side. 
1 strange thing for me was that I was inserting timestamps from the past and it seems Kafka actually cleans those up right away. You can't just insert old timestamps for messages 🤷‍♂

**Comment by tvoinarovskyi** [comment]
Hope it helped.
