### ISSUE TITLE
Order of magnitude performance degradation when inside a container

### ISSUE THREAD

**Issue by angrydexterous** [aio-libs/aiokafka#514]
When benchmarking aiokafka from inside a container and from outside of it to a container running kafka performance drops substantially. I'm wondering if anyone has any experience here on what might be going wrong

tests:
ipeft : faust container to kafka container *47.5 GBits/s*

aiokafka benchmark in faust container to kafka container
python3 ./simple_produce_bench.py -b kafka -s 1000
*Avg 5284.0 m/s*

from host to kafka container
*Avg 31255.0 m/s*

**Comment by tvoinarovskyi** [comment]
Probably for some reason the C extension failed to build in the container. I would recommend to build with -vvv pip and look at the output. aiokafka is written to degrade to pure python if C extension fails.

**Comment by tvoinarovskyi** [comment]
If you have some errors on C side compilation I could probably assist.

**Comment by angrydexterous** [comment]
Confirmed. Thank you very much!
