### ISSUE TITLE
How to know when the partition state has been updated

### ISSUE THREAD

**Issue by aure-olli** [aio-libs/aiokafka#523]
I've been working on a way to merge several topics by partition while ensuring the order with one partition (Basically a mergeSort of topics, which has strangely never been done). The working code can be seen here: https://github.com/aure-olli/aiokafka/blob/master/test_merge.py

A merge sort means consuming the same partition of different topics in a strict order. To avoid blocking the consumption in case of one the topics has no new message, I need to eventually emit messages of other topics after a certain amount of time (when estimated that all the future messages will be higher than the current ones).

I'm using `offset` and `highwater` of a `TopicPartitionState` to know if a partition of a topic is currently consumed. However, there's no clue on how fresh is this information. And since this information won't be updated as long as it has messages in cache, it can potentially be really old. I had to add a `timestamp` parameter, and update when `highwater` is updated by the fetcher.

```python
    @asyncio.coroutine
    def _proc_fetch_request(self, assignment, node_id, request):
[...]
        now_ms = int(1000 * time.time())
        for topic, partitions in response.topics:
            for partition, error_code, highwater, *part_data in partitions:
                tp = TopicPartition(topic, partition)
                error_type = Errors.for_code(error_code)
                fetch_offset = fetch_offsets[tp]
                tp_state = assignment.state_value(tp)
                if not tp_state.has_valid_position or \
                        tp_state.position != fetch_offset:
                    log.debug(
                        "Discarding fetch response for partition %s "
                        "since its offset %s does not match the current "
                        "position", tp, fetch_offset)
                    continue

                if error_type is Errors.NoError:
                    if request.API_VERSION >= 4:
                        aborted_transactions = part_data[-2]
                        lso = part_data[-3]
                    else:
                        aborted_transactions = None
                        lso = None
                    tp_state.highwater = highwater
                    tp_state.lso = lso
                    tp_state.timestamp = now_ms
[...]
```
Full diff here: https://github.com/aio-libs/aiokafka/compare/master...aure-olli:master
The `timestamp` parameter is used here: https://github.com/aure-olli/aiokafka/blob/df029a45f0e14f35b7a61b9afdd3af7b52be8f7c/test_merge.py#L365-L379

There may be other way to do that, this is the one that seemed the most simple to me.

**Comment by tvoinarovskyi** [comment]
That is a nice use case, will need to see though the whole code to give full feedback, but why do you need to know how old the information on fetch is? If you set max_fetch_timeout that would be predictable timeout. What is your sort key for those partitions, do you merge by timestamp?

**Comment by aure-olli** [comment]
Hi

From my understanding, a partition that has still data in cache will never be automatically fetched (https://github.com/aio-libs/aiokafka/blob/master/aiokafka/consumer/fetcher.py#L572), so `highwater` will never be updated. 

I cannot find anything about `max_fetch_timeout`. But the problem is about the time I need to consume all the data already fetched from kafka (in cache in python). This can take much time if we started from the beginning, and whereas it was all the data available when fetched at the time, new data could have arrived by the time it is computed. In my tests, I slow down data treatment on purpose, to check for this kind of corner case.

For sorting, anything is possible. The `StreamSorter` class uses timestamp by default but in my test I use a number retrieved from the message. It is even possible to have higher level choice of which message to treat first.

**Comment by tvoinarovskyi** [comment]
I ment `fetch_max_wait_ms` to control the maximum blocking time.
Went through your code, for one, please do not inherit from aiokafka classes if possible, there is no way to guarantee backward compatibility in that case.

About highwater, yes it will not be updated unless the partition is fetched, but if you only need to understand if there are still messages or not (not the whole lag) you should be good without knowing how old that info is. If there are messages in cache - there will be something returned without blocking. Maybe I missunderstood your intension. Anyway you can use offset API to get latest offset of a partition without consuming. 

I think you should not rely on aiokafka cache of messages. Just consume messages you can into your own cache and pause the partition if you fill like it's too much. Just be sure to handle commit carefully.

**Comment by aure-olli** [comment]
Let's consider 2 topics (topic1 and topic2) with 1 partition each. My problem is the following: I'm merging 2 topics. I have one message from topic1, but cannot fetch any from topic2. What do I do ? How long should I wait before processing the message from topic1 without comparing it with a message from topic2 ?

- If I always wait a fixed amount of time, or for the next poll, I'll just do so after each message of topic1, so my processing will be too slow for streaming.
- If I always choose to proccess the message, maybe there are already messages in topic2 and I just need to wait for the poll request, so I'll break the order.

What I do is
```
if topic2.consumed 
    # msg1 is clearly too old already and should be 
    # processed before any future message of topic2
    if msg1.timestamp + delay <= topic2.last_poll:
        process(msg1)
    # msg1 is pretty recent, so sleep until it gets too old
    elif msg1.timestamp + delay > now:
        sleep(now - (msg1.timestamp + delay))
    # msg1 is too old, but we need to check if topic2 has new message first
    else:
        topic1.wait_for_poll()
```
Currently, for `topic1.wait_for_poll()` I just wait for 100ms, since there's no callback.

But for `topic2.last_poll`, my options are:
- Uselessly call `consumer.offsets_for_times({"topic2": -1})` to build `topic2.last_poll` (with the time of the request), whereas the `Fetcher` is already doing such a request regularly.
- Consider that when `topic2.offset == topic2.highwater` for 200ms, `topic2.last_poll = now - 200ms`
- Having a `timestamp` in the subscription state.

**Comment by tvoinarovskyi** [comment]
I do see your example, it makes sense. Lets consider the case where we add a last_poll to each partition. In your example if topic2 partition is updated long ago, say 10s ago, what would you do? Wait? How long?

The problem here is that Kafka protocol is not really ment to be consumed per partition. It blocks if no data is present for consumption, but only for 1 node. That is how the protocol is designed, we use 1 socket per node and only 1 request at a time is allowed. Maybe we will need to introduce something like connection pool support... 

I would not mind adding a last_poll_timestamp interface, it's sensible, but for me it seems like the solution would be more complex, you need more control over the consumption and maybe pooling...

**Comment by aure-olli** [comment]
I know the "one request per node" limit, but with a decently low `fetch_max_wait_ms`, this is not a problem as the missing partitions will be included in the next request, which will come right after the previous one finished waiting. And when it finally arrives, I can consume all the messages of the other topics which are old enough. So at most 2 requests to wait to know if the partition is still empty, which is reasonable. 

My script is already working pretty well, whereas there's only one kafka node, so only one request at a time. It survives to repetitive restarting workers, and catching back with live stream from begining. The only other way would be to have a callback on every request response (I could then save my own timestamp).

**Comment by tvoinarovskyi** [comment]
Ok, lets go with a timestamp interface. Will you be able to do a PR for it? To me it seems like the same interface as `highwater()`. Do note, that tp_state is not a public API and may change in the future.

**Comment by aure-olli** [comment]
It actually makes much sense in the example (https://github.com/aure-olli/aiokafka/blob/timestamp_pr/docs/consumer.rst#consumption-flow-control), as non polled partitions don't have `highwater` update, so it's impossible to know when they start lagging behind.

**Comment by tvoinarovskyi** [comment]
@aure-olli Did this fix cover all you needed to support the merger for your use-case? If so we could close the ticket)

**Comment by aure-olli** [comment]
Thanks, that's all I needed :)
