### ISSUE TITLE
Improve documentation for Producer header support

### ISSUE THREAD

**Issue by andreportela** [aio-libs/aiokafka#566]
I spent some time trying to debug this and searching the internet. 

I was trying to pass headers like
`headers = [("key", "value"), ...]` or `headers = [(b"key", b"value"), ...]`

In the end, the right way to do it is `headers = [("key", b"value"), ...]`. I finally found it in a test on #471 
Where can we document this? I would be happy to open a PR.

**Comment by tvoinarovskyi** [comment]
I would be grateful if you could. I agree we need to document this behaviour, as it's far from obvious.

**Comment by andreportela** [comment]
Anywhere in particular? Or should I just dig a little and put it where I see fit?

**Comment by tvoinarovskyi** [comment]
For one it should be described in API reference here https://aiokafka.readthedocs.io/en/stable/api.html?highlight=headers#aiokafka.AIOKafkaProducer.send. You can update it using the docstring https://github.com/aio-libs/aiokafka/blob/master/aiokafka/producer/producer.py#L364.

Maybe a few words in producer docs, as it's more a problem to send proper structure than to read what you got.
