### ISSUE TITLE
Why producer does not send immediately?

### ISSUE THREAD

**Issue by scientistnik** [aio-libs/aiokafka#570]
I have microservice, who send message in kafka when triggered some event. Time between event and message in kafka is critical.

In this case I push several messages in kafka:
```python
async def init(host):
    global kafka_host
    global producer

    kafka_host = host

    producer = AIOKafkaProducer(
        loop=asyncio.get_event_loop(),
        bootstrap_servers=kafka_host,
    )
    await producer.start()


async def push(topic, value, key=None):
    # do something hurd

    data = msgpack.packb(value, use_bin_type=True)
    print("start push")
    await producer.send_and_wait(topic, data, key=encode_key(key))
    print('finish push')

async def start():
    await init('192.168.1.1:9092')
    for i in range(30):
        print("ensure next")
        asyncio.ensure_future(push("mytopic", data[:10], i))

loop = asyncio.get_event_loop()
loop.run_until_complete(start())
```

result:
```
$ python main.py
ensure next
ensure next
ensure next
...
ensure next
start push
start push
start push
start push
start push
start push
start push
start push
start push
start push
start push
start push
start push
start push
...
start push
finish push
finish push
...
finish push
$
```

if change `for i in range(10000):` nothing change.
```
ensure next
...
start push
...
finish push
...
```

How to make a producer send without waiting for the rest (sync version producer.send_and_wait)?

**Comment by bt-wil** [comment]
You would just want to use [asyncio.gather()](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather)
```
async def start():
    await init('192.168.1.1:9092')
    coros = [push("mytopic", data[:10], i) for i in range(30)]
    await asyncio.gather(*coros)
```

**Comment by scientistnik** [comment]
Nothing change

It is imitate receive event to service:
```python
for i in range(30):
```
`asyncio.gather` don't help me. I don't know when service receive next event. But I noticed when several events come in one time, `aiokafka` wait all calls `producer.send_and_wait`.

I need synchronous methods to send to kafka.

**Comment by tvoinarovskyi** [comment]
Try your code with this change. I hope it will help.

```python
async def init(host):
    global kafka_host
    global producer

    kafka_host = host

    producer = AIOKafkaProducer(
        loop=asyncio.get_event_loop(),
        bootstrap_servers=kafka_host,
    )
    await producer.start()


async def push(topic, value, key=None):
    # do something hurd

    data = msgpack.packb(value, use_bin_type=True)
    print("start push")
    await producer.send_and_wait(topic, data, key=encode_key(key))
    print('finish push')

async def start():
    await init('192.168.1.1:9092')
    for i in range(30):
        print("ensure next")
        asyncio.ensure_future(push("mytopic", data[:10], i))
        await asyncio.sleep(0)  # <-- You need to let the loop spin so it could send the messages.

loop = asyncio.get_event_loop()
loop.run_until_complete(start())
```

**Comment by tvoinarovskyi** [comment]
Will try to give some more explanation here, hope it helps. 

Technically the message will have some delay before it's sent, sorry for now having enough explanation in the documentation. I tried to describe it here https://aiokafka.readthedocs.io/en/stable/producer.html#producer-client, but it is far from perfect. 

Kafka is designed to produce "batches" of messages, not 1 message. That is how the protocol is structured. If you have only 1 node of Kafka there is no way to send 2 batches "at once", you need to ACK the first batch to send out the next one (protocol is synchronous). That is how _order_ is guaranteed in the partition. Usually, it only takes a few milliseconds of latency to deliver the batch and send out a new one, so you still see the message really fast after sending.

There are some ways to get around the problem, for example, the **max.in.flight.requests.per.connection** configuration in other libraries would allow you to send out more batches without waiting for a response, but that would only lower network latency, the server would still process those requests one at a time. Sadly _aiokafka_ does not support it atm.

If you have problems feel free to ask, will be glad to figure out something for your case. 👍

**Comment by scientistnik** [comment]
> Try your code with this change. I hope it will help.
> 
> ```python
> async def init(host):
>     global kafka_host
>     global producer
> 
>     kafka_host = host
> 
>     producer = AIOKafkaProducer(
>         loop=asyncio.get_event_loop(),
>         bootstrap_servers=kafka_host,
>     )
>     await producer.start()
> 
> 
> async def push(topic, value, key=None):
>     # do something hurd
> 
>     data = msgpack.packb(value, use_bin_type=True)
>     print("start push")
>     await producer.send_and_wait(topic, data, key=encode_key(key))
>     print('finish push')
> 
> async def start():
>     await init('192.168.1.1:9092')
>     for i in range(30):
>         print("ensure next")
>         asyncio.ensure_future(push("mytopic", data[:10], i))
>         await asyncio.sleep(0)  # <-- You need to let the loop spin so it could send the messages.
> 
> loop = asyncio.get_event_loop()
> loop.run_until_complete(start())
> ```

result:
```python
ensure next
start push
ensure next
start push
ensure next
start push
...
finish push
finish push
finish push
finish push
...
```
This work at is should with `await asyncio.sleep(0.01)`

**Comment by tvoinarovskyi** [comment]
@scientistnik Yes, so the idea is to give it a few spins to run the loop, so it could connect and send out data. In the application, you should not have any problems, it should send out the message right away, there is no delay by default (linger_ms=0 by default), only network latency.
Hope this solves your concerns.
