### ISSUE TITLE
Support for sasl mechanism: SCRAM-SHA-256

### ISSUE THREAD

**Issue by SukiCZ** [aio-libs/aiokafka#571]
Hello,

kafka-python \<recently\> [implemented](https://github.com/dpkp/kafka-python/pull/1918) support for SCRAM-SHA-256 mechanism. I would love to see aiokafka supporting it as well.
Thanks.

**Comment by tvoinarovskyi** [comment]
Does not sound too complicated, want to try doing it? I think the code for authentication is simple and described as standalone classes you can test. See here https://github.com/aio-libs/aiokafka/blob/master/aiokafka/conn.py#L524. It already handles all IO and all you need to do is copy this ScramClient from KafkaPython and glue it all together, plus some doc changes if you have time.

**Comment by tvoinarovskyi** [comment]
I am willing to answer any questions to help in the process.

**Comment by SukiCZ** [comment]
@tvoinarovskyi Thanks for offering me a help - I guess I'll need it.

The changes in PR are working just fine on my machine but I have issue setting up test runner. I suspect that either ZooKeeper should be configured for `SCRAM-SHA-*` as well or [this command](https://github.com/Dabz/kafka-security-playbook/blob/master/scram/up#L8) need to be run before tests - either way - I wasn't able to achieve that.

Any guidance would be appreciated. Thanks!

**Comment by tvoinarovskyi** [comment]
@SukiCZ Thanks! Yea, never thought about the test runners, will take a look to see what is missing, probably the commands are the thing missing.

**Comment by Neustradamus** [comment]
@SukiCZ: Thanks a lot for all about SCRAM.

Can you edit your main PR #588 description with the good issue number?
It is 571.

Note that @ran-ka has found a bug: https://github.com/aio-libs/aiokafka/pull/789

Linked to:
- https://github.com/scram-xmpp/info/issues/1
