### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by ultrabug** [aio-libs/aiokafka#572]
Hi

Since https://github.com/aio-libs/aiokafka/commit/f69b3378f5816fbb6c2b020823bd0acaeb898949 we are waiting for a new tag/release to use this straight from PyPi

Could you please make that happen? :) Thanks !

**Comment by tvoinarovskyi** [comment]
Yea, probably will review it and make a release soon. Thanks for the bump)

**Comment by ultrabug** [comment]
Hi @tvoinarovskyi ; friendly reminder please

**Comment by tvoinarovskyi** [comment]
@ultrabug https://github.com/aio-libs/aiokafka/issues/575#issuecomment-581785688 seems like a bad one, will try to wrap it up and release. Sorry again :(

**Comment by ultrabug** [comment]
Hello @tvoinarovskyi I hope you're doing well; this is yet another friendly reminder please

**Comment by tvoinarovskyi** [comment]
@ultrabug  Hey, I was away from the project for some time and need to be sure master is stable enough. Give me a bit of time, will definitely do it. Sorry for the trouble! ^^

**Comment by ls-jad-elkik** [comment]
Any chance you could release current master as an alpha or release candidate in the meantime? Thanks!

**Comment by tvoinarovskyi** [comment]
Done. Release 0.6.0 on pypi.
