### ISSUE TITLE
Return RequestTimeoutError handling in commit messages

### ISSUE THREAD

**Issue by tvoinarovskyi** [aio-libs/aiokafka#584]
Thanks to @FedirAlifirenko for pointing out.

You can receive an error ```OffsetCommit failed for group XXX on partition XXX with offset XXX: RequestTimedOutError``` from this line https://github.com/aio-libs/aiokafka/blob/master/aiokafka/consumer/group_coordinator.py#L1043

Before 0.4.0 there was a handler for this exception, but was mistakenly removed. Need to return handling with marking coordinator dead. This will match Java client behaviour. https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L1164

**Comment by FedirAlifirenko** [comment]
@tvoinarovskyi looks like resolved
