### ISSUE TITLE
import aiokafka fails with latest kafka-python library

### ISSUE THREAD

**Issue by anantkaushik1989** [aio-libs/aiokafka#590]
Steps to reproduce -

- pip3 install kakfa-python
- check kafka-python is latest version (2.0.0 or above)
- pip3 install aiokafka
- open python3 interpreter
- import kafka

Error results as 'ImportError: kafka.errors has no attribute ConnectionError'

ConnectionError is in aiokafka/errors.py, but not in latest kafka-python code base on github.

https://github.com/aio-libs/aiokafka/blob/master/aiokafka/errors.py#L71

https://github.com/dpkp/kafka-python/blob/2.0.1/kafka/errors.py - The commit shows clearly ConnectionError is deprecated.

**Comment by tvoinarovskyi** [comment]
Will look into this for 0.6.0. Thanks!

**Comment by anantkaushik1989** [comment]
Thank you Taras. May I ask when is 0.6.0 planned for release?

**Comment by tvoinarovskyi** [comment]
@anantkaushik1989 I want to do it this week, but I am hesitant to promise that as my time schedule is quite horrible. Will keep you posted )

**Comment by anantkaushik1989** [comment]
Thank you so much Taras for the update. Please let me know if I can assist in any way to help you in this. I can raise a small PR with deprecating this exception, if that is fine :)

Btw, awesome module. Really makes life so easy for use cases which are IO intensive 👍

**Comment by tvoinarovskyi** [comment]
@anantkaushik1989 If you could replace all usage of ConnectionError from aiokafka.errors package to KafkaConnectionError that would be a great PR. Import also change to:
```python
try:
    from kafka import KafkaConnectionError
except ImportError:
    from kafka import ConnectionError as KafkaConnectionError
```

It should solve the issue. Also bumping kafka-python dependency would be great, as most would want the latest version anyway.
