### ISSUE TITLE
[Question] Healtchecks in Kubernetes?

### ISSUE THREAD

**Issue by aorumbayev** [aio-libs/aiokafka#604]
What is the correct way to check connection status of Producers and Consumers within the scope of liveness or readiness probes when used in Kubernetes?

The `_closed` parameter doesn't always seems to be true. For instance `_closed` on Consumer will remain True even If broker will suddenly die (the consumer will also stuck in infinite reconnection loop).

**Comment by tvoinarovskyi** [comment]
I don't think we have any open API's to check if the consumer is Healthy, but in my mind there are 2 causes for failure: error in Consumer/Producer code, network/node failure.

In the 2nd case we could just connect to the broker and ask it something (say a metadata request or poll 1 message on Consumer). You will need to create a new consumer to be sure it reconnects. Or use a private API, but be sure to pin the version of aiokafka.

On the other hand software failures are harder, you need to check 'progress' of your consumer/producer. If you are quite certain there should always be traffic in the system, just count number of messages. If not you can look at real lag for the partitions you are consuming. See offset and highwater. If the LAG is larger than X and does not decrease - something is wrong.

**Comment by aorumbayev** [comment]
@tvoinarovskyi thanks for the reply! :-) 
Closing issue
