### ISSUE TITLE
More Consumer example snippets

### ISSUE THREAD

**Issue by tvoinarovskyi** [aio-libs/aiokafka#64]
Java's API docs contain some useful examples to work with the consumer (https://kafka.apache.org/0101/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html). As ``aiokafka`` does some a bit different it would be useful to place a counter-example for each in our docs

**Comment by Drizzt1991** [comment]
Changed it into a new documentation in `new_docs` branch. Should be ready for release 0.3.0. It needs some API changes so the examples don't look to strange. (like add seek_to_end, seek_to_beginning etc.)

**Comment by Drizzt1991** [comment]
Fixed in #157
