### ISSUE TITLE
Readme for lz4 compression use out-of-date

### ISSUE THREAD

**Issue by lowjiajin** [aio-libs/aiokafka#645]
**Describe the bug**
Kafka-python has transitioned from using `lz4tools` + `xxhash`, to `python-lz4` in [this PR](https://github.com/dpkp/kafka-python/pull/1057/files). But `aiokafka`'s Readme still requests the installation of the former.

Not doing so is the cause of bugs: https://github.com/dpkp/kafka-python/issues/1047. I personally encountered a vague `kafka.errors.UnknownError: [Error -1] UnknownError` when using aiokafka downstream in Faust.

**Expected behaviour**
Expected `aiokafka`'s ["Optional LZ4 install" section](https://aiokafka.readthedocs.io/en/stable/#optional-lz4-install) to work. It did not. Installing the latest [`lz4`](https://pypi.org/project/lz4/) instead, as suggested by `kafka-python`, resolve the error.

Would be happy to make a PR to update the docs.

**Comment by elrik75** [comment]
I've lost 15 days of my life on a `none_dealloc` crash without a f** traceback :)
It was caused by `lz4tools`. I'm SO disappointed that the doc was not updated. Now with `lz4` it works like a charm.

**Comment by ods** [comment]
`pip install 'aiokafka[lz4]'` should work now for code in master. `xxhash` actually may still be needed when used with old brokers, but I believe we can remove it from documentation anyway.

**Comment by CanD42** [comment]
with version 0.9.0 `aiokafka[lz4]` doesn't work anymore. Was it removed again?

`WARNING: aiokafka 0.9.0 does not provide the extra 'lz4'`

**Comment by ods** [comment]
> with version 0.9.0 aiokafka[lz4] doesn't work anymore.

Sorry, it was a packaging bug in 0.9.0. Should be fixed in [0.10.0](https://pypi.org/project/aiokafka/0.10.0/)
