### ISSUE TITLE
sdist tarball (version 0.7.0) on pypi contains pre-compiled shared objects for python3.7

### ISSUE THREAD

**Issue by toabctl** [aio-libs/aiokafka#681]
**Describe the bug**

When downloading https://files.pythonhosted.org/packages/19/a7/c8b9c764ca4cf3ce7e5f773716575622b368430922cb054eef5b6a257476/aiokafka-0.7.0.tar.gz and then looking at the content:

```
$ tar tfz aiokafka-0.7.0.tar.gz |grep .so
aiokafka-0.7.0/aiokafka/record/_crecords/cutil.cpython-37m-x86_64-linux-gnu.so
aiokafka-0.7.0/aiokafka/record/_crecords/default_records.cpython-37m-x86_64-linux-gnu.so
aiokafka-0.7.0/aiokafka/record/_crecords/legacy_records.cpython-37m-x86_64-linux-gnu.so
aiokafka-0.7.0/aiokafka/record/_crecords/memory_records.cpython-37m-x86_64-linux-gnu.so
```

Theses files should not be included in a source tarball. This is a problem when trying to package the sdist tarball eg. for python3.8 . In that case, RPMs autodetection of requirements would still require python3.7:

**Comment by ods** [comment]
`aiokafka.egg-info` directory and autogenerated by cython `.c` files shouldn't be included too.

**Comment by asvetlov** [comment]
Many libraries (aiohttp included) are shipped with pre-generated `.c` files. It allows building tarball without cython installed. I don't know how is the requirement important though.

**Comment by toabctl** [comment]
`.c` files should be included. I'm talking about compiled share objects. Thanks for the fix!
