### ISSUE TITLE
[QUESTION] Release 0.7 break support of python <3.7

### ISSUE THREAD

**Issue by MainRo** [aio-libs/aiokafka#697]
The release note indicates that support for python <= 3.5 is dropped. However aiokafka now used dataclasses. This is a feature only available from python 3.7. As a consequence, the support of pypy is broken (It may work with the latest 3.7 release though).

Is it intended to also drop support for python 3.6 and not just 3.5 ?

**Comment by ods** [comment]
The problem is already [fixed](https://github.com/aio-libs/aiokafka/commit/07e9bd3a3511cdb55fc2dafcda1dc9eea5bca88c) in master

**Comment by MainRo** [comment]
Thanks, that's great !
