### ISSUE TITLE
[QUESTION] Using inside a FastAPI application

### ISSUE THREAD

**Issue by m4nuC** [aio-libs/aiokafka#714]
Hi,

I am trying to start up a consumer inside a [FastAPI startup event](https://fastapi.tiangolo.com/advanced/events/). The code looks like this:
```
async def consume():
    consumer = AIOKafkaConsumer(
        'topic',
        loop=asynio.get_running_loop(),
        client_id="experiment_consumer",
        bootstrap_servers=f"server:port",
        enable_auto_commit=False,
    )
    await consumer.start()
    async for msg in consumer:
        print("consumed: ", msg.topic, msg.partition, msg.offset,
                msg.key, msg.value, msg.timestamp)

@app.on_event('startup')
async def app_startup():
    asyncio.create_task(consume())
```

I would expect that code to print the messages however it does not. If I restart the FastAPI server then all the points will get printed at once.

Any ideas on what might be going on here?

Thanks a lot

**Comment by marcosschroh** [comment]
@m4nuC 

You can use our framework [kstreams](https://kpn.github.io/kstreams/) which it integrates really well with FastAPI. Our driver is `aiokafka`. Here is the [code example](https://github.com/kpn/kstreams/tree/master/examples/fastapi-webapp)
