### ISSUE TITLE
[QUESTION] Handling deserialization errors in "value_deserializer" on consumer

### ISSUE THREAD

**Issue by dokzlo13** [aio-libs/aiokafka#744]
Hello! I have some problems with value_deserializer logic. 
My main question - how to handle deserialization errors, which happens in "value_deserializer" callback?

For example, I use [pydantic](https://github.com/samuelcolvin/pydantic) in my project, and want it to do deserialization work for me. Also, I'm trying to add validation errors handling to my consumer. But if deserialization error happens, ```AIOKafkaConsumer```  raises error and tries to read this message again.  This leads to an infinite error occurrence for this message. 
Can i handle this error in proper way and skip incorrect messages by using "value_deserializer". Or maybe move deserialization logic to upper level, and deserialize data after receiving message, like ```struct = deserialize(message.value)```?

### Code example

```python
from aiokafka import AIOKafkaConsumer
from pydantic import BaseModel, ValidationError


class DeserializationError(Exception):
    pass


class MyStruct(BaseModel):
    id: int
    mydata: str


def deserialize(data: bytes) -> MyStruct:
    try:
        model = MyStruct.parse_raw(data.decode("utf-8"))
    except ValidationError as e:
        raise DeserializationError("Error parsing data") from e
    else:
        return model


async def consume():
    consumer = AIOKafkaConsumer(
        "my_topic",
        bootstrap_servers="localhost:9092",.
        value_deserializer=deserialize,
        group_id="my_group",
    )
    await consumer.start()
    while True:
        try:
            message = await consumer.getone()
        except DeserializationError:
            print("Deserialization error!")
            continue
        else:
            print(message)

if __name__ == '__main__':
    import asyncio
    loop = asyncio.get_event_loop()
    loop.run_until_complete(consume())

```

Topic input:

```
$ ./kafka-console-producer.sh --bootstrap-server localhost:9092 --topic my_topic                      
>{"id":1, "mydata": "hello"}
>WRNOGFORMAT!!!
>
```

Printed:

```
$ python myconsumer.py
ConsumerRecord(topic='my_topic', partition=0, offset=0, timestamp=1621605995707, timestamp_type=0, key=None, value=MyStruct(id=1, mydata='hello'), checksum=None, serialized_key_size=-1, serialized_value_size=27, headers=())
Deserialization error!
Deserialization error!
Deserialization error!
... <Repeating forever>
```

**Comment by paulefoe** [comment]
Hi, I'm not an expert on this, but my intuition is that you can always commit messages manually.

```python
consumer = AIOKafkaConsumer(
    "my_topic",
    loop=loop, bootstrap_servers='localhost:9092',
    group_id="my_group",           # Consumer must be in a group to commit
    enable_auto_commit=False,      # Will disable autocommit
    auto_offset_reset="earliest",  # If committed offset not found, start
                                   # from beginning
)
...
try:
            message = await consumer.getone()
        except DeserializationError:
            print("Deserialization error!")
            await consumer.commit()
            continue
        else:
            print(message)

```

This is what I usually do with pydantic:

```python
...
    async for msg in consumer:
        try:
            MyStruct.parse_raw(msg.value)
        except Exception:
            logger.exception(
                'consumer decoding: failed',
                extra={'data': str(msg.value)}
            )

        await consumer.commit()
```

Let me know if that helps and which way you decided to go.

**Comment by dokzlo13** [comment]
Hi, @paulefoe, thanks for response. 
I tried first workaround, but results are the same. "Manual" commits on errors not solving issue with infinite wrong message reading. 

Second workaround, as expected, can solve this problem. But I'm interested in solution with using built-in callback "value_deserializer". Perhaps there are more options to make it work as expected?

**Comment by paulefoe** [comment]
I've looked a little bit more into it and it seems like the answer is no.

You can see it here:
https://github.com/aio-libs/aiokafka/blob/master/aiokafka/consumer/fetcher.py#L248

It first fetches the record and does deserializing inside `self._consumer_record(tp, record)` and only then move the topic offset further. It means that if there is an exception in deserializing part no progress could be made.

One thing you can do is not to raise exception ie:

```python

def deserialize(data: bytes) -> MyStruct:
    try:
        model = MyStruct.parse_raw(data.decode("utf-8"))
    except ValidationError as e:
        return e.errors
    else:
        return model

```
Let me know if this works

**Comment by dokzlo13** [comment]
The proposed solution works as expected, but requires type checking, instead of exception handling. This leads to the fact that without additional logic, the entire trace of stack is lost. 

Example:
```python
def deserialize(data: bytes) -> MyStruct:
    try:
        model = MyStruct.parse_raw(data.decode("utf-8"))
    except ValidationError as e:
        return DeserializationError("Error parsing data") # could not "return <...> from exception", only raise
    else:
        return model

# ...
while True:
    message = await consumer.getone()
    if isinstance(message.value, DeserializationError):
        print("Deserialization error!")
        continue
    else:
        print(message)
```

Other example - is using wrappers around result in deserializer callback (like in [rust](https://doc.rust-lang.org/std/result/), or implemented in [python](https://github.com/dbrgn/result)). This is actually same solution. 

```python
from result import Ok, Err, Result

def deserialize(data: bytes) -> Result[MyStruct]:
    try:
        model = MyStruct.parse_raw(data.decode("utf-8"))
    except ValidationError as e:
        return Err(DeserializationError("Error parsing data"))
    else:
        return Ok(model)

# ...
await consumer.start()
while True:
    message = await consumer.getone()
    if not isinstance(message, Ok):
        print("Deserialization error")
        continue
    else:
        print(message)
```

In my opinion - both are not best solutions for production-grade code. For my project I choose "manual" deserialization of data (without "value_deserializer" callback). 

Overall, adding proper serialization exceptions handling for aiokafka library looks like good idea for PR.

**Comment by paulefoe** [comment]
I'm not sure what stack trace you're talking about. This is pydantic exception and everything is available inside e.errors.
I agree about the type checking, but few things here to note:
1. I don't think the overhead is really big from checking what you have received if at all
2. I think of deserialization of something flexible and permissive. This shouldn't really fail. Someone changes the data structure they send to kafka and your deserialization fails. But you probably only need a few fields out of the whole message (and they still present).
3. You can try new shiny python pattern matching too!

Overall, I'm not in a position to make any decision on that. 
If you want to submit or request a PR for change then I'm not the correct person to make a decision.
Maybe @tvoinarovskyi or @fabregas can help.
