### ISSUE TITLE
[QUESTION] How to use the pause api | cannot get instance check to work

### ISSUE THREAD

**Issue by kevinvdbekerom** [aio-libs/aiokafka#751]
When using the Consumer.pause api, I am unable to get it to work. Whatever I try, I keep getting instance errors.

`partitions = list(consumer.assigned())`
`await consumer.pause(partitions)`

This results in TypeError('partitions must be TopicPartition namedtuples')

I would have expected this to work. But I suppose since aiokafka has its own TopicPartition it works differently...
How should I pause the consumer for a given topic? (partitions for topic returns a list of ids, not TopicPartitions)

**Comment by ods** [comment]
`pause()` method accepts each partition [as separate argument](https://aiokafka.readthedocs.io/en/stable/api.html#aiokafka.AIOKafkaConsumer.pause), but not as list. So you have to write it as `await consumer.pause(*partitions)`.
