### ISSUE TITLE
How should one consume your mypy stubs?

### ISSUE THREAD

**Issue by Trolldemorted** [aio-libs/aiokafka#771]
#638 says mypy suport should be there, but no documentation exists and mypy complains in downstream packages (`Cannot find implementation or library stub for module named "aiokafka"`). How can I make mypy recognize your types in consuming packages?

**Environment (please complete the following information):**
 - aiokafka version (`python -c "import aiokafka; print(aiokafka.__version__)"`): 0.7.1
 - kafka-python version (`python -c "import kafka; print(kafka.__version__)"`): 2.0.2

**Comment by ods** [comment]
Taras just started to add mypy support, only two files were formatted so far: 
https://github.com/aio-libs/aiokafka/pull/638/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R8
https://github.com/aio-libs/aiokafka/pull/638/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R27

But this shouldn't prevent you from checking your code that uses aiokafka, just add the following options to mypy configurations:
```
ignore_missing_imports = True
check_untyped_defs = True
```

**Comment by Trolldemorted** [comment]
Sorry, I saw the old merge request and https://github.com/aio-libs/aiokafka/tree/master/stubs/kafka and assumed that these stubs were complete.

I know I can ignore missing imports, but a fully typed aiokafka would be very nice to have :)

**Comment by pawelswiecki** [comment]
What is the situation with stubs now?

**Comment by PeterJCLaw** [comment]
@ods just wondering if there's any update here? It's great to see that this codebase is adding type annotations to itself, however currently those annotations aren't published for users. Would you be open to a PR which adds support for that (i.e: adding a `py.typed` marker file)?

**Comment by ods** [comment]
@PeterJCLaw, thank you for desire to help with development. We're planning to add `py.typed` after adding annotations in the primary public API (producer, consumer).
