### ISSUE TITLE
[QUESTION] Graceful shutdown

### ISSUE THREAD

**Issue by moritz89** [aio-libs/aiokafka#819]
What is the recommended method to perform a graceful shutdown for consumers (and producers)?

Would a simple global variable / Django signal at the end of the loop suffice?

In the field, when K8s pods are replaced, the process is killed with a SIGINT. Handling that signal is possible in Python, the question is, how can the async consumer iterator be stopped, so that the current message is allowed to be finished processing and the consumer then shutdown? The `finally` will be called which allows the consumer.stop() to be executed, but the result of the current message would be undefined behavior.

The code handling the message processing is designed to handle _at least once_ semantics, however, reducing the need to recover from such instances would reduce latency and improve through put especially in the case of continuous deployment.

**Comment by ods** [comment]
The best way to guarantee producer or consumer is properly closed is to use `async with AIOKafkaProducer(…) as producer:`/`async with AIOKafkaConsumer(…) as consumer:` pattern.

AFAIK, [k8s uses SIGTERM](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination), so you have to install a handler for it. And in case you run your code via shell script, beware it doesn't propagate signals by default.

**Comment by ods** [comment]
> […] how can the async consumer iterator be stopped, so that the current message is allowed to be finished processing and the consumer then shutdown?

1. Create a global `asyncio.Event()` object.
2. Set it from signal handler
3. Use `while True` loop instead of `async for`
4. Wait for new message (`consumer.getone()`) or stop event is set, which comes first, with `asyncio.wait()`.
5. Break the loop if stop event is set.

**Comment by moritz89** [comment]
Thanks for the pointers! As a reference for others, propagating the signal from a shell script is described by [Veithen here](http://veithen.io/2014/11/16/sigterm-propagation.html).

**Comment by ods** [comment]
> As a reference for others, propagating the signal from a shell script is described by Veithen here.

Nowadays it seems to be much simpler: `--init` option to `docker run` or [`init: true` line](https://docs.docker.com/compose/compose-file/compose-file-v3/#init) in `docker-compose.yml`.

**Comment by jainal09** [comment]
Can anyone share a demo python code snippet for this. I am really struggling to implement this

**Comment by ods** [comment]
Yes, your code is fine. Also when your handling is idempotent it's safe to rase an exception (usually `SystemExit`) from signal handler.

**Comment by jainal09** [comment]
The problem that I observed with this code is, when I am spinning 4 containers of this same code or even start 4 python scripts of this same code, on a kafka topic with 4 partitions (4 is just random could be anything).  Each time I start a new script, a rebalance occurs that is ideal but after 4 scripts start 1 or 2 scripts/ consumer are never assigned any partitions. I don't know why, because in normal scenarios whenever a consumer joins a consumer grp a rebalance occurs and the load should be distributed among all the consumers. Here, some consumers gets assigned to 2 partitions and some just sits idle to 0 partitions.
