### ISSUE TITLE
[QUESTION] next release?

### ISSUE THREAD

**Issue by qdamian** [aio-libs/aiokafka#840]
Hi, do you know when there may be a new release? I'm interested in zstd compression support which was added in https://github.com/aio-libs/aiokafka/pull/801

**Comment by ods** [comment]
We are working on it

**Comment by marcosschroh** [comment]
Hi, I am happy to help to maintain this project. We are using `aiokafka` on prod and we want to avoid a `fork`. Do you think it is possible?

**Comment by ods** [comment]
@marcosschroh There are several bugs that prevents us from releasing straight away, first of all [one related to zstd compression](https://github.com/aio-libs/aiokafka/issues/843).

**Comment by ods** [comment]
@tvoinarovskyi @asvetlov Please consider adding @marcosschroh to maintainers. Here is [a contribution from him](https://github.com/aio-libs/aiokafka/pull/845) waiting for review.

**Comment by harrycis** [comment]
Any update on the release? The last release was still using cython 0.29.20, with a bug that break aiokafka on M1 Mac https://github.com/cython/cython/pull/3921

**Comment by ods** [comment]
0.8.0 is just released. But beware, as it still has [a known bug with zstd](https://github.com/aio-libs/aiokafka/issues/843).
