### ISSUE TITLE
Generated documentation for `AIOKafkaConsumer` on `readthedocs.io` doesn't have `getone` or `getmany`

### ISSUE THREAD

**Issue by andersglindstrom** [aio-libs/aiokafka#853]
The documentation for [`AIOKafkConsumer` on `readthedocs.io`](https://aiokafka.readthedocs.io/en/stable/api.html#aiokafka.AIOKafkaConsumer) does not have documentation for the `getone` and `getmany` methods.

The source code for those methods has docstrings, so I'm expecting the generated docs to include that documentation.

**Comment by ods** [comment]
It seems that’s no longer the case. Feel free to reopen if you find any problem.
