### ISSUE TITLE
[QUESTION] Message reading by consumer 

### ISSUE THREAD

**Issue by unregistered33** [aio-libs/aiokafka#872]
Hello, friends.!
Please explain to me how to read the messages transmitted by the producer while the consumer was not working? I'm trying the simple-producer and simple-consumer examples. First I run simpleproducer, and then simple-consumer and the message does not come. If simple-consumer is already running and I'm running simple-producer, then the messages come normally. How can I read the messages sent by the producer while the consumer was not working (for some reason)?

**Comment by ods** [comment]
Looks like you start reading from the end. What `auto_offset_reset` do you use?
