### ISSUE TITLE
support pattern subscription in kafka

### ISSUE THREAD

**Issue by vicanfon** [aio-libs/aiokafka#874]
**Describe the solution you'd like**
Current version only support subscriptions to topics, but I want it to support topics following a pattern. This is supported by python-kafka and it is an additional parameter when subscribing.

**Comment by tvainika** [comment]
You can use `AIOKafkaConsumer.subscribe(topics=(), pattern='PREFIX.*', listener=None)` for pattern subscription. See https://aiokafka.readthedocs.io/en/stable/api.html#aiokafka.AIOKafkaConsumer.subscribe
