### ISSUE TITLE
Recursion in Fetcher.next_record() causes RecursionError

### ISSUE THREAD

**Issue by Artimi** [aio-libs/aiokafka#90]
There is recursion in `Fetcher.next_record()` that unhlandled may lead to `RecursionError` eventually. In our  environment we are using single `AIOKafkaConsumer` for consuming multiple topics. But we want to get message only from desired topics, that's why we've used `AIOKafkaConsumer.getone(*partitions)` with `partitions` that consists of all `TopicPartitions` that corresponds to topic we want to consume in given coroutine. Using `AIOKafkaConsumer.getone()` calls `Fetcher.next_record()` where I encountered said problem. We may consume multiple partitions in `Fetcher` but it is synchronized by only one `Fetcher._wait_empty_future` (that serves to synchronization on new data). Here follows `next_record()` method:
```python
@asyncio.coroutine
def next_record(self, partitions):
	for tp in list(self._records.keys()):
		if partitions and tp not in partitions:
			continue
		res_or_error = self._records[tp]
		if type(res_or_error) == FetchResult:
			message = res_or_error.getone()
			if message is None:
				# We already processed all messages, request new ones
				del self._records[tp]
				self._notify(self._wait_consume_future)
			else:
				return message
		else:
			# Remove error, so we can fetch on partition again
			del self._records[tp]
			self._notify(self._wait_consume_future)
			res_or_error.check_raise()
	# No messages ready. Wait for some to arrive
	if self._wait_empty_future is None or self._wait_empty_future.done():
		self._wait_empty_future = asyncio.Future(loop=self._loop)
	yield from asyncio.shield(self._wait_empty_future, loop=self._loop)
	return (yield from self.next_record(partitions))   
```
Imagine that this coroutine is awaited multiple times with partitions corresponding to each topic we have. Each of this coroutines awaits at one line before end on `asyncio.shield`. When **one**, e.g. first, topic receives data it sets `self._wait_empty_future` and **all** of those waiting coroutines recurses to the method `next_record` and again await on the same line until that first topic receives data. When this happens 1000 times (standard recursion limit) and no message comes for other topics all those coroutines fails with `RecursionError` because they get down one level each time the first topic receives data.

One thing that can solve this bug is removing recursion from `Fetcher.next_record()`. Maybe it would be even better to synchronize that coroutines per partition and not all by one `_wait_empty_future` but that would be maybe to complex and expensive.

**Comment by Drizzt1991** [comment]
Thanks, will take a look at those on the weekend.

**Comment by Drizzt1991** [comment]
Should be fixed in master. Will do a release today, pls check it out )

**Comment by Artimi** [comment]
It seems ok. Memory is not rising anymore, recursion error did not occur. Thank you for the fix!

**Comment by Drizzt1991** [comment]
np
