### ISSUE TITLE
[QUESTION] Plans for migrating from kafka python to confluent-kafka-python

### ISSUE THREAD

**Issue by jainal09** [aio-libs/aiokafka#910]
I noticed that kafka-python is no longer being supported and won't be updated for future versions of kafka, as stated in the open issue https://github.com/aio-libs/aiokafka/issues/908 and confirmed by https://github.com/dpkp/kafka-python/issues/2290. Although kafka is backward compatible, it's important for our active kafka-client project to support the latest features and functionalities.
Therefore, I'm exploring alternative solutions to this problem. One possible solution is to replace the deprecated kafka-python function calls with the confluent-kafka-python. After overviewing the aio-kafka source code, it seems feasible to replace the calls to kafka-python with confluent-kafka to match the required functionalities.
I would appreciate your thoughts on this matter.

**Comment by ods** [comment]
We're considering another option, to incorporate needed parts of kafka-python into aiokafka source. The confluent-kafka-python is based on librdkafka, which is very different approach.
