### ISSUE TITLE
Python 3.12.0 compatibility issue

### ISSUE THREAD

**Issue by pawel-swiecki-saucelabs** [aio-libs/aiokafka#928]
**Describe the bug**
There is a Python 3.12.0 compatibility issue of aiokafka's dependency, namely [kafka-python](https://github.com/dpkp/kafka-python). The issue has been reported [here](https://github.com/dpkp/kafka-python/issues/2401) and there already is a fix waiting to be reviewed [here](https://github.com/dpkp/kafka-python/pull/2398). (By the looks of open issues and open PRs it seems the library is not actively maintained.)

**Expected behaviour**
No `ModuleNotFoundError: No module named 'kafka.vendor.six.moves'` when importing `aiokafka` on Python 3.12.0.

**Environment**
 - Python version: 3.12.0
 - aiokafka version: 0.8.1
 - kafka-python version: 2.0.2 
 - Kafka Broker version: not relevant

**Reproducible example**
```bash
$ cat Dockerfile
FROM python:3.12-bullseye
RUN python -m venv venv
RUN ./venv/bin/pip install aiokafka
ENTRYPOINT ["/venv/bin/python", "-c", "import aiokafka"]

$ docker run -it $(docker build -q .)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.12/site-packages/aiokafka/__init__.py", line 3, in <module>
    from .abc import ConsumerRebalanceListener
  File "/venv/lib/python3.12/site-packages/aiokafka/abc.py", line 2, in <module>
    from kafka import ConsumerRebalanceListener as BaseConsumerRebalanceListener
  File "/venv/lib/python3.12/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.consumer import KafkaConsumer
  File "/venv/lib/python3.12/site-packages/kafka/consumer/__init__.py", line 3, in <module>
    from kafka.consumer.group import KafkaConsumer
  File "/venv/lib/python3.12/site-packages/kafka/consumer/group.py", line 13, in <module>
    from kafka.consumer.fetcher import Fetcher
  File "/venv/lib/python3.12/site-packages/kafka/consumer/fetcher.py", line 19, in <module>
    from kafka.record import MemoryRecords
  File "/venv/lib/python3.12/site-packages/kafka/record/__init__.py", line 1, in <module>
    from kafka.record.memory_records import MemoryRecords, MemoryRecordsBuilder
  File "/venv/lib/python3.12/site-packages/kafka/record/memory_records.py", line 27, in <module>
    from kafka.record.legacy_records import LegacyRecordBatch, LegacyRecordBatchBuilder
  File "/venv/lib/python3.12/site-packages/kafka/record/legacy_records.py", line 50, in <module>
    from kafka.codec import (
  File "/venv/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
    from kafka.vendor.six.moves import range
ModuleNotFoundError: No module named 'kafka.vendor.six.moves'
```

**Comment by Arthur264** [comment]
+

**Comment by SpudInNZ** [comment]
Also waiting on this, is there any ETA? Thanks.

**Comment by kPsarakis** [comment]
kafka-python is not actively maintained or getting any of the new features (deprecated) https://github.com/dpkp/kafka-python/issues/2290. We should help the developers of aiokafka towards the standalone package goal as discussed here https://github.com/aio-libs/aiokafka/issues/908

**Comment by ods** [comment]
@kPsarakis I'm at finish line of merging kafka-python's code into aiokafka. Are you willing to review test it?

**Comment by kPsarakis** [comment]
@ods Yes, let me know how I can help.

**Comment by ods** [comment]
@kPsarakis https://github.com/aio-libs/aiokafka/pull/932

**Comment by jainal09** [comment]
@ods I saw that your PR #932 was merged. But, I see that I am still getting this error with the latest merge code which is not dependent on the kafka-python project

**Comment by ods** [comment]
> But, I see that I am still getting this error with the latest merge code which is not dependent on the kafka-python project

Do you have kafka-python installed and import it from your code directly? Please show traceback with the latest code from master.

**Comment by AntonOfTheWoods** [comment]
Looks like this is good to go - any chance of a release?

**Comment by ods** [comment]
> Looks like this is good to go - any chance of a release?

There are more issues to fix before release. One is the problem with python-snappy (replacing it with cramjam is in process), and another is moving away from setup.py (not so simple due to Cython).

**Comment by ods** [comment]
One more step towards new release with Python 3.12 support: https://github.com/aio-libs/aiokafka/pull/940. It would be very helpful if those using aiokafka with Snappy and/or ZStandard compression check it with their applications.

**Comment by SpudInNZ** [comment]
Speaking for us @ods it's much easier for us to test a new version if you release to pypi as a beta.

**Comment by AntonOfTheWoods** [comment]
Yep, and the quicker this gets out, the higher the likelihood `kafka-python` won't get a 3.12 release, and we can let it die the death it deserves!

**Comment by ods** [comment]
Ok, [here is pre-release](https://pypi.org/project/aiokafka/0.9.0rc0/)

**Comment by SpudInNZ** [comment]
Even using the new version, I'm getting the same import error.
```
fb-sf-etl-sfapi-1  |   File "/opt/project/app/interfaces/kafka/topic_creator.py", line 6, in <module>
fb-sf-etl-sfapi-1  |     from aiokafka.admin import AIOKafkaAdminClient, NewTopic  # type: ignore
fb-sf-etl-sfapi-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/aiokafka/__init__.py", line 3, in <module>
fb-sf-etl-sfapi-1  |     from .abc import ConsumerRebalanceListener
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/aiokafka/abc.py", line 2, in <module>
fb-sf-etl-sfapi-1  |     from kafka import ConsumerRebalanceListener as BaseConsumerRebalanceListener
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/kafka/__init__.py", line 23, in <module>
fb-sf-etl-sfapi-1  |     from kafka.consumer import KafkaConsumer
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/kafka/consumer/__init__.py", line 3, in <module>
fb-sf-etl-sfapi-1  |     from kafka.consumer.group import KafkaConsumer
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/kafka/consumer/group.py", line 13, in <module>
fb-sf-etl-sfapi-1  |     from kafka.consumer.fetcher import Fetcher
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/kafka/consumer/fetcher.py", line 19, in <module>
fb-sf-etl-sfapi-1  |     from kafka.record import MemoryRecords
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/kafka/record/__init__.py", line 1, in <module>
fb-sf-etl-sfapi-1  |     from kafka.record.memory_records import MemoryRecords, MemoryRecordsBuilder
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/kafka/record/memory_records.py", line 27, in <module>
fb-sf-etl-sfapi-1  |     from kafka.record.legacy_records import LegacyRecordBatch, LegacyRecordBatchBuilder
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/kafka/record/legacy_records.py", line 50, in <module>
fb-sf-etl-sfapi-1  |     from kafka.codec import (
fb-sf-etl-sfapi-1  |   File "/usr/local/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
fb-sf-etl-sfapi-1  |     from kafka.vendor.six.moves import range
fb-sf-etl-sfapi-1  | ModuleNotFoundError: No module named 'kafka.vendor.six.moves'
```

**Comment by ods** [comment]
And one more, [0.9.0rc1](https://pypi.org/project/aiokafka/0.9.0rc1/)

**Comment by ods** [comment]
Let's move this discussion to the topic for the prerelease: https://github.com/aio-libs/aiokafka/discussions/948
