### ISSUE TITLE
0.9.0 zstd codec depends on cramjam but missing in documentation

### ISSUE THREAD

**Issue by iamwrm** [aio-libs/aiokafka#952]
**Describe the bug**

Hi. I found zstd compression support needs cramjam

https://github.com/aio-libs/aiokafka/blob/881851783673e927591ba274a7703c9b52d387ac/aiokafka/codec.py#L10C19-L10C19

But the doc still says `pip install aiokafka[zstd]`, while 0.9.0 doesn't even have this option.

https://github.com/aio-libs/aiokafka/blob/881851783673e927591ba274a7703c9b52d387ac/docs/index.rst?plain=1#L127

**Environment (please complete the following information):**
 - aiokafka version (`python -c "import aiokafka; print(aiokafka.__version__)"`): 0.9.0
 - Kafka Broker version (`kafka-topics.sh --version`): redpanda
 - Other information (Confluent Cloud version, etc.):

If this bug does confirm to exist, I would love to open a PR to fix the doc.

**Comment by ods** [comment]
Should be fixed in [0.10.0](https://pypi.org/project/aiokafka/0.10.0/)
